### ISSUE TITLE
Numbas and Blackboard

### ISSUE THREAD

**Issue by anthonyyoud** [numbas/Numbas#100]
This issue is mainly so that we're aware of a possible problem with running Numbas and Blackboard.

Graeme Chester is using Numbas for one of his EECE courses.  Practice mode ran successfully last week (no results stored in Grade centre).  This week, in assessed mode (results stored in Grade centre), he says two students have had errors when running the exam.  The attempt is marked as "in progress" in the Grade centre.

The error is `error no such interface supported`.

Don't think we've seen this before, but it may be the same as the IE deadlock problem.  I'll add more to this issue if I get more info from Graeme.

**Comment by christianp** [comment]
Closing this because either it's a BB bug that went away after they switched to the new SCORM player, or it was a bug in a very old version of IE.
