### ISSUE TITLE
Process for downloading csv result summaries

### ISSUE THREAD

**Issue by Lycanic** [numbas/Numbas#1000]
I'm working on a branch #984 .  This is somewhat related to #420 .

The intention is to allow the collation of data for non-VLE-run exams in a cleaner way than a current process (where a teacher may for example ask students to download their results as a pdf and then have to manually type this out).

At the moment, there is a button on the results page to download a csv file summarising the attempt, this can be encrypted with a password given by the author. In the exam package there is a page for collecting and analysing these files. As it stands, the page allows the upload of files and download of decrypted versions of those files.

I am now working on the display of data within the page itself and collation of student's results into one easy-to-use csv.

To do:
- [x] Collate student data
- [x] Read encryption/decryption password from exam definition
- [x] For each level of detail, download a csv corresponding to displayed data
- [ ] Tidy headers
- [x] Deal with random question orders
- [ ] Make it look nice
- [ ] Clear instructions (beginning from 'get students to download their data and send it to you')
- [ ] (Stretch) If the data the student downloads contained the full SCORM data model, then allow reviewing an attempt

Levels of detail
- [x] Student name - total score
- [x] Student name and score for each question
- [x] Full collated results for every student (headers, row for each student)
- [ ] (Stretch) Full attempt timeline

**Comment by christianp** [comment]
This was done in #1016
