### ISSUE TITLE
Issue with mathematical expression questions

### ISSUE THREAD

**Issue by ugonj** [numbas/Numbas#1012]
Certain mathematical expression questions fail correct answers. For example, a simple question asking for $(-6)^n$ fails that answer. See [here]( https://numbas.mathcentre.ac.uk/question/142736/equation-test/).

To reproduce: 

1. create a new question, with a new part, "Mathematical Expression". 
2. In correct answer, enter "(-6)^n". 
3. Run the question and enter (-6)^n in the box then submit.

Note that the "Testing" tab gives a few failures in the marking algorithm that might give a hint: either the algorithm is looking for a `rhs` component that doesn't exist, or for a `ruleTree` function/component that doesn't exist.

**Comment by christianp** [comment]
Thanks for reporting this. It turned out there was a bug in the logic for exponentiating a `decimal` value, which is used when you take an integer to a non-integer power.
