### ISSUE TITLE
Define min and max on ranges

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#1028]
It should be possible to recover the start and end of a `range` value using the `min` and `max` functions. At the moment, it tries to convert the range to a list and return the min and max of that, which is inefficient and doesn't work for continuous ranges or ranges where the end is not a multiple of the step size from the start.

**Comment by Siddhant-Kashyap** [comment]
can i go for it .will you please assign it to me

**Comment by Siddhant-Kashyap** [comment]
okay working on it
