### ISSUE TITLE
WCAG 1.4.13: floating warnings for answer inputs must be dismissable

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#1031]
At the moment a floating box showing warning messages appears when you focus an answer input.

I think that pressing <kbd>Esc</kbd> should hide the floating warning box. They should reappear when the input is focused again.

**Comment by itlallou** [comment]
Hello!I'd like to contribute to this issue

**Comment by christianp** [comment]
@itlallou thanks for offering to help!
Please look at [our guidelines on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/).

I think that we can implement this by adding a case for the escape key to [the PartDisplay's `inputEvents` keypress handler](https://github.com/numbas/Numbas/blob/master/themes/default/files/scripts/part-display.js#L460), which would call the PartDisplay's `hideWarnings` method.

**Comment by christianp** [comment]
Actually, I've just tried this and the `keypress` needs to change to `keyup` - the Escape key doesn't produce a `keypress` event.

**Comment by christianp** [comment]
Fixed by #1035.
