### ISSUE TITLE
Sidebar height could be set using viewport height

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#1051]
I noticed today that on the large desktop PCs in one of our new clusters, the sidebar only uses 50-60% of the available height - could this use the viewport height to place the buttons at the bottom, logo at the top and use whatever's left for the question list?

**Comment by christianp** [comment]
I've realised I closed this, but didn't really engage with expanding the question list.

**Comment by christianp** [comment]
My first go at expanding the question list highlighted how awkward it is that the footer makes the page scroll separately to the question content:

[Screencast from 20-10-23 16:10:43.webm](https://github.com/numbas/Numbas/assets/19513/1ae2c591-2395-4376-bfe8-e0239fb13b73)

After removing the footer, it all fits neatly:

[Screencast from 20-10-23 16:12:22.webm](https://github.com/numbas/Numbas/assets/19513/557802df-c84e-4072-bb49-7fd7ed70cbb9)

So I suppose a question is: where else can we put the footer? Maybe it could go in the sidebar?

![image](https://github.com/numbas/Numbas/assets/19513/d08f0a09-33ab-4a04-a6ac-6a3a0355bde5)

That makes it even more noticeable though, which I'm not sure we want.

**Comment by chrismgraham** [comment]
I think it's OK, but does make the bottom of the sidebar a bit busy.

Could it go at the bottom of the question content column, below the bottom navbar?
