### ISSUE TITLE
Number entry: add an input hint "Write your answer as a fraction", shown when "must be reduced" is false

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#1069]

**Comment by carlortiz** [comment]
Hi @christianp!

Happy holidays! I would like to help out with this issue.

I've made changes and attempted to make a pull request. However, I was denied permission.

Here are screenshots of the changes I've made. Please let me know if I did something wrong, or you would like more information. Thank you!

Screenshots:
![Screenshot 2023-12-24 at 5 52 20 PM](https://github.com/numbas/Numbas/assets/45545195/af11833a-8f86-462b-9aad-8e60011674e5)
![Screenshot 2023-12-24 at 5 57 42 PM](https://github.com/numbas/Numbas/assets/45545195/7eae3c1a-3fc1-42a0-adae-a0d33141622e)

**Comment by alexander-kuruvilla** [comment]
Hi @christianp, has this issue been resolved? I see that someone has attempted to solve this before but the issue seems to be open? 
Thanks

**Comment by christianp** [comment]
@alexander-kuruvilla no, it hasn't been resolved.

**Comment by zpotthoff** [comment]
Hi @christianp, I assume this has not been resolved yet since it's not closed? I'm happy to submit a PR if it's still open.
Thanks!

**Comment by mthakurt** [comment]
Hi @christianp, is this issue still open? I would love to take it up if it is!

**Comment by christianp** [comment]
@mthakurt sorry, this was resolved by @zpotthoff but I didn't notice that it hadn't been closed automatically.
Thanks for offering to help! There are still a few other issues labelled "good first issue" that you could take on.
