### ISSUE TITLE
Submitting empty mathematical expression is considered "answered"

### ISSUE THREAD

**Issue by Spruce8913** [numbas/Numbas#1093]
Minimal working example [here](https://numbas.mathcentre.ac.uk/exam/share/edit/9f0405e9-7838-4745-848b-54eefbc37aa4)

In a multipart question, students rely on the "Answered" or "Partially Answered" overview for the exam, to see what questions still need attention. When submitting an empty answer for a number entry, the part is marked as unanswered; when submitting an empty answer for a mathematical expression, the part is marked answered.
![image](https://github.com/numbas/Numbas/assets/49608009/861a9a3c-063b-4787-9181-234dec7a7e5f)

Would it be possible to check for empty submissions of all part types, to make partially answered labels more reliable?

**Comment by christianp** [comment]
The difference isn't that part a is a mathematical expression part: it's because it's a gap-fill.

So gap-fill parts should not be marked "answered" if any of the gaps failed to be marked.
