### ISSUE TITLE
 In questions with a single part, show the "(not/partially) answered" text when feedback is not otherwise shown

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#1094]
It's in the part feedback box, just under the score.

**Comment by Lycanic** [comment]
Images for information:
A currently submitted single-part question looks like this:
![image](https://github.com/numbas/Numbas/assets/17724612/8eb1ddbd-64b8-4604-8e0e-e9d31080835d)
Whilst a multi-part shows 'Answered':
![image](https://github.com/numbas/Numbas/assets/17724612/3fbc8c9a-52d1-401d-b67f-0196d145398a)
