### ISSUE TITLE
Unexpected scroll behaviour when opening steps

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#1098]
There seems to be some unpredictable scrolling behaviour when opening steps. On this question, for example,. https://numbas.mathcentre.ac.uk/question/153089/vector-mcq/preview/ it seems that:

- if you're above the steps in part a), with the question prompt and header fully in view, the step opens as expected, with no change in your position on the screen 
- if you've already scrolled past the heading for a),  then the window jumps down to the start of b)

Is it possible that the window is set to move to the next visible heading, or something like that, when the steps open, so goes to b) because the heading for a) has left the window?

Let me know if you want a video, it's easier to see than write about!

**Comment by christianp** [comment]
Which browser did you see this in? It doesn't seem to happen in Firefox. A video would be helpful.
