### ISSUE TITLE
Diagnostic mode has html issue in navmenu

### ISSUE THREAD

**Issue by benbrawn** [numbas/Numbas#1111]
In the diagnostic mode, there is this piece of code in the HTML for the exam:
`<a class="navmenu-brand"></a>`
which is an empty link which does nothing, except makes the logo the second element in a grid, hence moves it over to the right half of the container. I think this is a mistake. We think this would be  
`<div class="navmenu-brand>`
 since this is what is in the non-diagnostic mode. The div should end later on after the image.

Hopefully, the pictures attached help
<img width="727" alt="html_issue" src="https://github.com/user-attachments/assets/95feed50-d18a-438a-8379-49fc365b0fff">
<img width="314" alt="logo" src="https://github.com/user-attachments/assets/ae4576c5-6dec-40f0-9ba7-4a5617d078a6">

**Comment by christianp** [comment]
Whoops! I mustn't have checked diagnostic mode the last time I changed the nav menu.
Thanks for reporting this!
