### ISSUE TITLE
Remove the "save all answers" button and show the "save answer" button above the feedback for a part which is the only one in the question

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#1118]

**Comment by Harshrj1502** [comment]
I want to work on this issue can you explain somewhat where to make changes

**Comment by christianp** [comment]
@Harshrj1502 thanks for offering to help! Please have a look at [our advice on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code).

I think that in [`question-nav.xslt](https://github.com/numbas/Numbas/blob/1a89f9bd56b3d37210189234376ae47eca8b9450/themes/default/templates/question-nav.xslt#L5) the button to submit all parts should be removed, and in [`part-display.js`](https://github.com/numbas/Numbas/blob/master/themes/default/files/scripts/part-display.js#L350), the condition `p.question.display.parts().length<=1` should be removed, so that the submit button is shown next to the part.

**Comment by christianp** [comment]
Please read the page I linked to above, with instructions on how to set up a development environment.
