### ISSUE TITLE
German locale files out of date

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#1121]
It seems that the German locale files are out of date and (correspondingly) POEditor does not show all strings that need to be translated (e.g. part.show feedback).

**Comment by christianp** [comment]
Sorry, I normally update the translations each time I tag a release, and I forgot to do it this time. Thanks for reminding me!
I've updated both the locale files in this repo and poeditor. I'll try to remember to check poeditor again in a few weeks.

**Comment by ugoertz** [comment]
Excellent, thanks! I translated all the new strings on POEditor.

(I do not know how the locale files are deployed. If there is a chance to get the Numbas runtime translations into the Numbas editor fairly soon, that would be perfect, since our term starts next week... If that's not possible, I will find a way to work around it.)

**Comment by christianp** [comment]
Thanks! I've updated the locale files.
