### ISSUE TITLE
gauss_jordan_elimination

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#1125]
I am confused about the function [gauss_jordan_elimination](https://docs.numbas.org.uk/en/latest/jme-reference.html#gauss_jordan_elimination). If I feed `matrix([0, 1], [1, 0])` into this function I would expect to get the unit matrix of size 2, but instead Numbas complains that "this matrix is not invertible" (even though, in this case, it obviously is invertible ...).

In fact, in https://github.com/numbas/Numbas/blob/1a89f9bd56b3d37210189234376ae47eca8b9450/runtime/scripts/math.js#L3400 it checks whether it can divide by the upper left entry and stops when this is not possible. Shouldn't it swap rows in that case (and also, in general, allow for the first column being zero)?

Best regards, Ulrich

**Comment by ugoertz** [comment]
PS. Correspondingly, the `inverse` function suffers from similar problems and cannot handle `matrix([0, 1], [1, 0])`.

PPS. I think the `reduced_row_echelon_form` function in the Linear Algebra extension works correctly, and could replace the `gauss_jordan_elimination`.

**Comment by ugoertz** [comment]
Thanks for the quick fix!

If the left part of the matrix is invertible then, I think, it will work correctly now, so in particular this fixes the `inverse` function.

I still think that usually the term "Gauss-Jordan elimination" applies to an arbitrary matrix being put into reduced row echelon form (allowing for example that there are more rows than columns; and that the leading 1s can be "spread out" further rather than ending up in the first columns).

Since the functionality is available in the Linear Algebra extension, it is maybe not needed here, but it might then be useful to document the assumption the current `gauss_jordan_elimination` makes on the matrix. (Or remove the function from the public interface since we can get the result using `inverse` (for a matrix `A`, multiply the inverse of the left hand square submatrix of `A` by `A`.)

**Comment by christianp** [comment]
You're right, I shouldn't have taken a shortcut!

I've copied the (reduced) row-echelon code from the linear algebra extension. I think I need to update that extension anyway, because the `Fraction` object it's expecting to use doesn't look like the one that's currently in the Numbas math library.
