### ISSUE TITLE
Display of distractors in m_n_x question 

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#121]
In an m_n_x question with more than one possible set of answers for each choice, such as that in git://gist.github.com/1671456.git,  distractors are only displayed for the choices for the first answer - not for any other. For example in the example in gist above (or the 3214 example 6a on inishmore, inishmore.ncl.ac.uk/MAS3214_20122013_CBA1_6a) the only distractors shown are for the selections on the True answer as it is the first in the set of answers. So if you choose false for a choice the corresponding distractor is not displayed.

**Comment by christianp** [comment]
m_n_x parts lost the ability to have distractors a while ago, so I'm closing this. I think I just couldn't work out how to make an editing interface for them! I'll open another issue asking for it to be put back in.
