### ISSUE TITLE
Marking equations of the form f(x)=a

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#192]
See MAS1141 CBA4_2.
The user is required to input the cartesian equation of a plane of the form ax+by+cz=d; a,b,c,d integers.
If you input any expression of the form f(x)=n (eg 10=1) then always marked as correct.  Anything with an equal sign is marked as correct.

**Comment by christianp** [comment]
I think this is best implemented as a custom part type "Define a function".
It'd take an answer in the form `f(name) = <expression in name>`, then compare with the correct answer by subbing values in for `name`.
