### ISSUE TITLE
Possibly confusing display of ln with abs?

### ISSUE THREAD

**Issue by anthonyyoud** [numbas/Numbas#254]
I've just seen a student who had entered ```ln abs(x)``` (essentially) as her answer.  Other than the fact that ```ln``` is typeset in italics, the pretty print gives the impression that this is correct.  It looks "more correct" than ```sin x``` or ```cos x```, for example, because of the addition of the vertical bars.  I've just educated her that she should be using parentheses for functions, i.e. ```ln(abs(x))```.  Do you think we need to do anything more about this?

**Comment by christianp** [comment]
The expected variable names setting would take care of this - they'd be warned that `ln` isn't an expected variable name.
