### ISSUE TITLE
Feature request: unordered input

### ISSUE THREAD

**Issue by msgj603** [numbas/Numbas#295]
I commented on this on the group forum, but I think it got missed. I would like to request another type of input called something like "unordered". This could work like gapfill except that the inputs are accepted in any order.

This would be a more natural way of entering mutliple answers, e.g. for quadratic equations.

**Comment by christianp** [comment]
Can you think of a question that wouldn't be accomodated by the "set entry" part proposed in #391? The difference here is that you want to have separate input fields, whereas the "set entry" part would have just one.

**Comment by christianp** [comment]
I'm closing this in favour of #391, which contains an idea for how this could be implemented.
