### ISSUE TITLE
Graphical question type

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#316]
By this is meant a question type which has a user input which cannot be edited directly by the user, but only changed using interaction with, for example, a JSXGraph diagram and moving things around in that. Since Numbas can already fill up user entry fields with values from such interactions and process them, there would seem to be two options: 1) Show the value created  to the user, but no editing allowed or 2)Do not display the value created.

**Comment by christianp** [comment]
There's no generic solution here.
