### ISSUE TITLE
Put dropdownlist back in

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#320]
There used to be a `displaytype` option for 1_n_x and m_n_2 parts, which let you ask for a list of radio/check boxes, or a drop-down list. I got lazy and removed the drop-down list support a while ago, so it should go back in.

**Comment by christianp** [comment]
Actually, if I put the code back in the runtime, we just need to make the option available in the editor again. I'll make an issue.

**Comment by abhanshgiri21** [comment]
hi,
i would like to work on this, how can i do this?

**Comment by christianp** [comment]
Hi,
Thanks for offering. I've written what needs to be done in the editor repository at numbas/editor#329

**Comment by christianp** [comment]
@extigy has finished the work on the editor, so this is now done.
