### ISSUE TITLE
map not working if used in the definition of a variable?

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#363]
See https://numbas.mathcentre.ac.uk/question/7022/test-map/

The variable a defined as map(k,k,0..3) gives an error, stack size exceeded, whereas the  function test() with the same definition  in Functions & rulesets works.

**Comment by christianp** [comment]
Sorry, broke this recently and fixed it but forgot to fix the version in the editor. Will fix it tomorrow morning.

On 22 Jan 2015 17:10, Bill Foster <notifications@github.com> wrote:

See https://numbas.mathcentre.ac.uk/question/7022/test-map/

The variable a defined as map(k,k,0..3) gives an error, stack size exceeded, whereas the function test() with the same definition in Functions & rulesets works.

**Comment by christianp** [comment]
Now fixed.
