### ISSUE TITLE
Creating polynomials in javascript

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#365]
An alternative method of creating a polynomial would use the same format as in JME i.e. Polynomial('x',c) where c is a list of coefficients rather than a dictionary. So the assumption would be that the index of the list gives the degree.

**Comment by christianp** [comment]
That's already there.

**Comment by BillFoster** [comment]
I tried it but the problem is that the code in the extension looks for d in the coefficient list and picks up "merge" and "contains" as well as the indices so doesn't return what is expected.


		for(var d in this.coefficients) {
			var c = this.coefficients[d];
			if(c!=0) {
				bits.push({degree:parseFloat(d),coefficient:c});
			}
		}

**Comment by christianp** [comment]
Ah, didn't read this properly and missed that you were talking about JavaScript.
