### ISSUE TITLE
JME part: allow checking values to be defined with a JME expression

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#398]
At the moment, you can just give a continuous interval and a number of points to pick. When this isn't good enough, you should be able to give a JME expression to generate a list of sample points.

A couple of examples I've been thinking of:
- when checking logical propositions, you should try all combinations of `true` and `false` for the variables. Something like `product([true,false],[true,false],...)`
- in modular arithmetic, only pick integers - fractions don't work.
- pick from different ranges for each variable.

Your expression should return a list of points to check. A "point" is a list giving values for each of the variables. (The editor should tell you which order to use)

**Comment by christianp** [comment]
This might enable #109

**Comment by chrismgraham** [comment]
One more example to add to that list:

- Give vector samples to allow expressions such as `dot(u,v)` to be evaluated.
