### ISSUE TITLE
Displaying logical expressions

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#405]
It is possible to build up a string which gives a logical expression and then evaluate it using the evaluate function evaluate(string,[list]) where list is the list of variables that have their values subbed into the expression and a truth value is obtained.
However, it seems that in order to display the logical expression that the student has to evaluate you need to use LaTeX logical operators. This is because using \simplify the brackets are stripped out in such expressions e.g. $\simplify{(a or b) and c}$ . This is in contrast to arithmetic operations e.g. $\simplify{(a + b) *c}$ where the brackets are kept. 
This makes the writing of such questions, with a  number of terms,  difficult and one answer would be to make sure that brackets are kept using \simplify in the case of logical operators. This would mean extending \simplify to logical expressions.

**Comment by christianp** [comment]
Please be very clear, with examples, about when you do and don't want brackets. 
`\simplify` should put brackets in only when they're needed to fix the order of operations. It's not impossible it gets it wrong, but I can't remember seeing it, and I don't have time to look into it myself.

**Comment by BillFoster** [comment]
I did give a very explicit example  $\simplify{(a or b) and c}$  in my original comment  which does not work,as expected returning the expression without any brackets. Clearly brackets are needed and this needs to be remedied at some point.
See https://numbas-editor.mas.ncl.ac.uk/question/1182/williams-copy-of-dealing-with-logical-symbols/

**Comment by christianp** [comment]
Give more examples, when you want brackets and when you don't.

**Comment by BillFoster** [comment]
Simply, if brackets are included in a logical expression then they should be retained. It is up tot the author to make sure the expression is what they intended.

**Comment by christianp** [comment]
That's not how the simplify system works, for good reasons. It would be a huge job to make it do that. Just work with strings and don't use simplify.
