### ISSUE TITLE
Boolean 'not' operator does not display correctly in Numbas.jme.display.texify

### ISSUE THREAD

**Issue by graemechester** [numbas/Numbas#422]
I have been experimenting with writing custom scripts to use JME for checking Boolean expressions, it seems to be working OK but the input box won't accept '!' or 'not' operators. The error message reads:-

`texOps[tok.name.toLowerCase(...)] is not a function`

I traced this through and found that  both ops are translated to 'not', though only '!' is define in texOps.
Both the editor and runtime are affected.

**Comment by christianp** [comment]
Whoops, can't think how long that's been broken! Fixed it. Thanks for letting me know.

**Comment by graemechester** [comment]
Thanks for the quick response – looks like no-one else is using Booleans!

Kind regards,
Graeme Chester
------------------------------------
Dr. E.G. Chester, School of EEE, Newcastle University
Tel: 0191 208 7325 Email: graeme.chester@ncl.ac.uk<mailto:graeme.chester@ncl.ac.uk>
