### ISSUE TITLE
Adaptive marking on a gapfill part should carry through to each of the gaps

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#429]
If possible, to say at the part level which variables used in the gap-fills in that part can be replaced by student answers.
This may not be possible if a gap-fill uses student answers from another gap-fill in the same part?

**Comment by christianp** [comment]
I think this means: in a part with multiple gapfills, give a list of variables at the part level which are replaced the same way in every gap.
Or do you mean you want something in the editing interface to tell you which variables are used?

**Comment by christianp** [comment]
I've changed the title to what I think this is about, and I agree that it would be good.
