### ISSUE TITLE
Failed simplification

### ISSUE THREAD

**Issue by vegardl** [numbas/Numbas#434]
I wanted to create a polynomial x^2+(a+b)x+ab where a and b are random.
When using simplify around the whole expression simplification sometimes fail, i.e. result in things like x^2 + -1x-20.

An example of this:
[https://numbas.mathcentre.ac.uk/question/13262/failed-simplification/](https://numbas.mathcentre.ac.uk/question/13262/failed-simplification/)

**Comment by christianp** [comment]
Thanks for this. I can't believe this bug has been in Numbas since the start, but it does seem to have been!

**Comment by vegardl** [comment]
Thanks!
If I had paid attention and followed the tutorial I would had written \simplify{x^2 + {a+b}x + {a*b}} and it would have worked...
