### ISSUE TITLE
Forbidden string in Mathematical Expression -> wrong answer

### ISSUE THREAD

**Issue by vegardl** [numbas/Numbas#435]
If "=" is a forbidden string in a mathematical expression, the problem is not correctly graded.

Example demonstrating the problem:
[https://numbas.mathcentre.ac.uk/numbas-previews/question-13321-forbidden-string/index.html](https://numbas.mathcentre.ac.uk/numbas-previews/question-13321-forbidden-string/index.html)

**Comment by christianp** [comment]
Whoops! I broke that while fixing the last thing. It didn't matter which string you forbade - the whole thing was broken.
While testing this, I also found another unpleasant but very subtle bug which somehow hadn't come up in all the years it's been hiding there, so thanks for making me look!

**Comment by vegardl** [comment]
Thanks for fixing this!
