### ISSUE TITLE
Dead links encountered in the question editor

### ISSUE THREAD

**Issue by henrikmidtiby** [numbas/Numbas#451]
Steps to reproduce:
1. Log in to numbas.mathcentre.ac.uk
2. Open a question to work on or create a new question
3. Click on one of the small blue question marks
4. You get a "Page does not exist" error, eg. this page http://numbas-editor.readthedocs.io/en/latest/exam-reference.html#term-pass-threshold

**Comment by henrikmidtiby** [comment]
For reference I think that the link should point to 
http://numbas-editor.readthedocs.io/en/latest/exam/reference.html#term-pass-threshold
The only difference is that "-" is changed to "/" between exam and reference.

**Comment by christianp** [comment]
Thanks for this. I've already got an issue in the editor repository at numbas/editor#312
