### ISSUE TITLE
Narrow screen: End exam button next to the Next question button

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#460]
It's not obvious, once you've finished the last question, how to end the exam - at the moment you have to open the menu.

**Comment by christianp** [comment]
Here's how it currently looks: 
![image](https://cloud.githubusercontent.com/assets/19513/19509688/e915b0dc-95d7-11e6-9331-fd74c706d298.png)
The End Exam button should appear to the right of the greyed-out "Next" button when we're on the last question.

**Comment by darshan934** [comment]
Hi,
I'd like to work on this.

**Comment by christianp** [comment]
Go for it! The relevant file is `themes/default/files/index.html`. Copy the existing "End exam" button, and add a `visible:` data-binding to make it visible only when we're on the last question.

**Comment by darshan934** [comment]
Thanks for the information, what will be the tag following visible (data-bind="visible:____") such that the end button only appears at the last question?

**Comment by janga1997** [comment]
I would like to work on this issue, but it seems like the file structure has changed since posting this issue. 
Can you help me with the new location of this issue?

**Comment by christianp** [comment]
The sidebar and the top nav bar are both in `themes/default/templates/nav.html`. 
You should copy the `endBtn` from https://github.com/numbas/Numbas/blob/master/themes/default/templates/nav.html#L51 to just after the "next question button" at https://github.com/numbas/Numbas/blob/master/themes/default/templates/nav.html#L67

It might be worth adding the class `btn-warning` to the new button, to make it look important.

If that looks weird, or we run out of space on small screens, this might need rethinking. Or we could hide the "next question" button when on the last question.
