### ISSUE TITLE
There should be an option on patternmatch parts to match a string literal, instead of writing a regular expression

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#461]
Regular expression syntax is complicated, and the vast majority of text match parts will only want to match a single string. There should be an option to match exactly the given string, rather than interpreting it as a regular expression.

**Comment by darshan934** [comment]
Hi, 
I'd like to work on this

**Comment by Divyanshu169** [comment]
Hey, I am a first timer and would like to take this up.Could you point out how to go about it?

**Comment by christianp** [comment]
Thanks for offering!

* In [bin/exam.py](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L832), add a property `matchMode`, with default value `regex`. Add corresponding lines to the `fromDATA` and `toxml` methods to load and output the value.
* In [runtime/scripts/parts/patternmatch.js](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/patternmatch.js#L33), add a line to loads the `matchMode` property
* change the [`mark` method](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/patternmatch.js#L107) to do a string equality check instead of using a regular expression when `matchMode` is `"exact"`. 
* You should still observe `this.settings.caseSensitive` - if that's set to `false`, both the student's answer and the correct answer should be converted to lower case before checking for equality.
* Trim whitespace off both the student's answer and the correct answer before checking.


Here are some example inputs:

| Correct answer | Student's answer | Case sensitive?  | Correct? |
|------------------|--------------------| ------------------| ----------|
| `"Hello there"`  | `"Hello there"`      | yes                      | yes         |
| `"Hello there"`  | `"hello there"`      | yes                      | no          |
| `"Hello there"`  | `"hello there"`      | no                      | yes          |
| `"   Hello there"`  | `"Hello there  "` | yes                     | yes         |
| `"hello."`           | `"hello!"`               | yes                     |no           |

**Comment by janga1997** [comment]
Hey, I would like to take up this issue. I assume this is still open?

**Comment by christianp** [comment]
Hi, thanks for offering. Yes, please have a go. It's a little bit complicated though, so please ask for help if you get stuck.

**Comment by janga1997** [comment]
@christianp I think you can close this issue.

**Comment by christianp** [comment]
@janga1997 you're right, thanks!
