### ISSUE TITLE
"Several from a list" part fails with a custom marking matrix 

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#479]
Adding a custom marking matrix to a "Several from a list" part generates an error: "The custom marking matrix expression is empty." See https://numbas.mathcentre.ac.uk/question/19880/several-from-a-list-with-marking-matrix/ 

Moreover, and presumably related, on refreshing the editor question the "custom marking expression" field does not appear to be saved, and instead displays "true".

**Comment by christianp** [comment]
A silly typo in the editor: I wrote `customMarking` instead of `customMatrix`.
