### ISSUE TITLE
"Answer must be reduced to lowest terms" option for number entry part

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#481]
There should be an option to require that the student's answer must be reduced to lowest terms when given as a fraction.
If the student's answer is not reduced, then partial credit should be applied.

To do this:

* add options `mustBeReduced` and `mustBeReducedPC` to the `NumberEntryPart` in [`bin/exam.py`](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L867) - you should add default values in [the class constructor](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L869), load values in [`fromData`](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L893), and store the values in [`toxml`](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L918). Look at how the other settings are loaded and saved.
* In `runtime/scripts/parts/numberentry.js`, load the setting [in the part constructor](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/numberentry.js#L39).
* in [`NumberEntryPart.mark`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/numberentry.js#L214), when `this.settings.mustBeReduced` is true, work out the numerator and denominator, and check that their gcd is 1 (Use [`math.gcd`](http://numbas.github.io/Numbas/Numbas.math.html#.gcd)). If not, apply the partial credit with [`this.multCredit(this.mustBeReducedPC)`](http://numbas.github.io/Numbas/Numbas.parts.Part.html#multCredit).

ref #380

**Comment by saurabhgoyaliitr** [comment]
Hello , I am new to Open source environment. I can clearly implement the GCD logic to find a number is in its lowest form or not but can you help with how to get started as this could be my first PR . thanks ,

**Comment by christianp** [comment]
Thanks for offering to take this on. First of all, have a look at [our guide to contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code), and try to [install a local copy](http://numbas.github.io/editor/) if you can. 

I'll expand the list of things to do at the top of this post.

**Comment by saurabhgoyaliitr** [comment]
Chris , You want me to install Numbas on my system or to fork your code ?

**Comment by christianp** [comment]
Both - install Numbas on your computer so you can check that any changes you make actually work, and fork the repository so that you can submit a pull request.

Have a look at the [GitHub Bootcamp](https://help.github.com/articles/fork-a-repo/).

**Comment by saurabhgoyaliitr** [comment]
Okay . Thanks

**Comment by saurabhgoyaliitr** [comment]
I am facing some problems with installation which I asked on Google group of Numbas. I will get to this work as soon as i get my issues cleared. Thanks

**Comment by shreab373** [comment]
can i take this up?

**Comment by christianp** [comment]
@shreab373 yep, if you make a pull request I'll take a look at it.

As I said above, first have a look at [our guide to contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code), and try to [install a local copy](http://numbas.github.io/editor/) if you can.
