### ISSUE TITLE
Option to name parts

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#494]
Rather than gaps being referred to as "gap N" in the feedback, it would be nice if the question author could name gaps, so it could say for example "Mean of the distribution: ...".
Suggested by David Wishart on the numbas-users list.

**Edit:** I've expanded this to include parts. Someone asked to name each of the parts in their question something like "Q42" and "Q43".

## To do this

* Add a `name` field to [`GapFillPart` in exam.py](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L1154).
* Load the name field in [gapfill.js](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/gapfill.js)
* Change the string [`part.gapfill.feedback header`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/parts/gapfill.js#L101) to use the gap's name instead of the number. If the name isn't set, still use "Gap N".

**Comment by parkcl** [comment]
Hi, I'd like to give this a try.

Should there be any constraints on the gap name (e.g. the length)?

**Comment by thakkardharmik** [comment]
Hi, I'd like to try and fix this issue. Please suggest how shall I go forward.

**Comment by christianp** [comment]
Hi @thakkardharmik I've outlined above what needs to be changed.
The first thing you should do is to get an instance of the Numbas editor running - see http://numbas.github.io/editor/

**Comment by christianp** [comment]
This relates to #463 - if parts have arbitrary labels, then "no label" is a special case of that.
