### ISSUE TITLE
Implies operator not properly documented

### ISSUE THREAD

**Issue by JoshuaCapel** [numbas/Numbas#501]
The builtin logical operator 'implies' contains the documentation for 'xor' instead of 'implies'.

https://github.com/numbas/Numbas/blob/94186edaa06cfc80ee7513f3673f2cc29a52331f/runtime/scripts/jme-builtins.js#L441

This is also not properly documented on the Numbas read-the-docs page. I will try to raise the issue there too.

**Comment by christianp** [comment]
Whoops! Thanks for pointing this out.
