### ISSUE TITLE
Vertical offset required for (resizable) matrix input when used as a gapfill

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#504]
When the option to allow students to change the size of a matrix is used as a gapfill, inline with other expressions, the additional height taken up by the resize box results in the matrix being misaligned vertically with the rest of the line. I can fix this in a single question using the following jQuery

`$(".matrix-input").has(".matrix-size").css( "margin-top", "-50px" ); `
`$(".type-matrix").has(".matrix-size").css( "padding-top", "50px" );`

I don't think there would be any harm adding something to the stylesheet long these lines.

The issue is illustrated here: https://numbas-editor.mas.ncl.ac.uk/numbas-previews/question-1931-matrix-size-as-an-inline-gapfill/index.html

**Comment by christianp** [comment]
I've had a go at this and it's just too hard! To do what Chris asks, we need the `.part.type-matrix` element to know it's going to allow resizing, but that information isn't available until we're inside that element.

We tried a couple of other options for resizing the matrix, without that bar:

* always add an additional row and column, and automatically shrink back when the last row or column is empty: it always looks like you've got a row/column left to fill in. The blank state looks like a fixed (m+1)x(n+1) layout, unless you style the additional cells differently, in which case it's not obvious you're supposed to type in them.
* buttons at the end of each row/column to add another column/row. We couldn't find a set of symbols and styling that made them look obviously clickable without explanation.

**Comment by christianp** [comment]
Fixed in #932
