### ISSUE TITLE
Getting around restrictions on question permissions

### ISSUE THREAD

**Issue by WoosterUK** [numbas/Numbas#505]
If you don't have permission to see a certain question, but you do have permission to see an exam containing it, you can get a copy of the question by downloading the source file of the exam and re-uploading it. This is probably not expected behaviour? Correspondence, with original report, below.

-----Original Message-----
We did discover a way (which may be useful should you need to do something similar): download the source file of the exam and re-upload it to NUMBAS. You magically obtain a copy (with edit access) of all questions in the exam.

Regards,
A

**Comment by christianp** [comment]
Hmm! What should the expected behaviour be?

**Comment by WoosterUK** [comment]
I don't really know! But I guess my assumption would be that if someone has given you access to the quiz but not the questions, they don't want you replicating the questions contained in the quiz. Or maybe that's the wrong assumption?

It was the wrong assumption here, as the colleague whose materials we were trying to access didn't know how to give us access to the questions but did give access to the quizzes containing them. We thought this was probably getting around the access controls rather than using them as intended.

**Comment by christianp** [comment]
I've just realised this issue should be in numbas/editor. Can you reopen it there please?
