### ISSUE TITLE
Some options for what's shown on the results page

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#506]
Particularly, David Wishart wants the option not to show the questions and advice on the printed version of the results page (they're hidden in the screen stylesheet).

There could be options to show/hide each of the other sections: student info, score breakdown, timing.

**Comment by stefpiatek** [comment]
I'd be up for giving this a go, have just set up the local instance so I'll have a toy around if no-one else has started.

**Comment by christianp** [comment]
Thanks! Let me know if you get stuck.

**Comment by christianp** [comment]
There are two halves to this:

* Add the option to the Numbas editor for exam authors.
* Make the Numbas compiler (this repository) load the option, and act on it when displaying the results.

In the Numbas editor, you'll need to add some settings to the Exam object, and make sure they get saved and loaded.

* In [editor/exam/edit.js](https://github.com/numbas/editor/blob/master/editor/static/js/exam/edit.js#L74), add an object `this.results_options = {showquestions: ko.observable(true), showadvice: ko.observable(true)}`
* Make sure those options are loaded and saved by the [Exam.load](https://github.com/numbas/editor/blob/master/editor/static/js/exam/edit.js#L276) and [Exam.toJSON](https://github.com/numbas/editor/blob/master/editor/static/js/exam/edit.js#L238) methods
* Add the options to the exam editor template, inside [the Feedback tab](https://github.com/numbas/editor/blob/master/editor/templates/exam/edit.html#L240).

Then, in this repo:
* In `exam.py`, load the options in [Exam.fromDATA](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L168) and produce some corresponding XML in [Exam.toxml](https://github.com/numbas/Numbas/blob/master/bin/exam.py#L220) (yes, it's a bit redundant to have to translate JSON to XML, but there are historical reasons)
* In `runtime/scripts/exam.js`, [load the options from the XML](https://github.com/numbas/Numbas/blob/master/runtime/scripts/exam.js#L47).
* Finally, in the default theme, you'll have to do something to [question.html](https://github.com/numbas/Numbas/blob/master/themes/default/templates/question.html) and the [print stylesheet](https://github.com/numbas/Numbas/blob/master/themes/default/files/resources/exam.css#L656) to only show questions or advice if the corresponding settings are turned on.

**Comment by christianp** [comment]
Implemented, thanks to @stuwilmur!
