### ISSUE TITLE
The mathematical expression part preview is applying simplification rules

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#510]
I'm not even sure it should apply `basic`.

Something like `-2*3*x + cos(x)` should be displayed as `- 2 \times 3 x + \cos(x)`, not `cos(x) - 6x`.

*To fix:*

* on [line 55 of `themes/default/files/scripts/parts/jme-display.s`](https://github.com/numbas/Numbas/blob/master/themes/default/files/scripts/parts/jme-display.js#L55), replace `p.settings.answerSimplification` with an empty string, `''`.

**Comment by rpirritano** [comment]
Is this still available?  If so, I can take it?

**Comment by christianp** [comment]
Thanks for offering but no, it's fixed. There are still [a few open issues that would make a good first contribution](https://github.com/numbas/Numbas/labels/good%20first%20issue).
