### ISSUE TITLE
Part warnings should be visible, but dismissable

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#511]
Some students don't think to mouse over the warning symbol, and it's not very accessible.
Instead, have the warning visible first, with a "dismiss" button. Clicking the button makes the warning go away but marks the part as dirty, so it has to be resubmitted.

**Comment by chrismgraham** [comment]
Our recent engineering test has further emphasised that students don't read these warnings. I wonder if it's possible as an alternative/addition to the above, to bring up the "Can not submit answer - check for errors" warning, as you would get entering a fraction into a number entry part?

**Comment by christianp** [comment]
The cases from the engineering test shouldn't have prevented submission - it's reasonable to use the wrong variable names, so allow submission.
Issue #345 would fix it - if we could only allow single-letter variable names, then we could prevent submission if the student uses a multi-letter variable name.
