### ISSUE TITLE
Results page: make it more obvious that questions can be clicked on to review

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#519]
Currently, the question results table in the default theme looks like this:
![screen shot 2018-01-09 at 08 30 23](https://user-images.githubusercontent.com/19513/34711448-5b1f4d10-f517-11e7-925a-29e42477ee14.png)
When you hover over a row, it's highlighted and you get a pointer:
![screen shot 2018-01-09 at 08 29 36](https://user-images.githubusercontent.com/19513/34711412-3db1028c-f517-11e7-9faa-dd44b703e7f5.png)

Parthasarati Dileepan didn't think this was obvious enough - unless you mouse over the rows, it looks static.

Possible ways of making it more obviously clickable:
* make the question number a link, so it gets the link colour. I don't think that makes enough of a difference.
* Add another column with a button labelled "review"

The results table is generated by [themes/default/templates/result.html](https://github.com/numbas/Numbas/blob/master/themes/default/templates/result.html#L5)

**Comment by prakharcipher** [comment]
I'd like to pick up this issue.

**Comment by reddysridhar53** [comment]
Can I work on this?

**Comment by donutsteele** [comment]
Is this issue still available to work on? I would like to give it a shot

**Comment by christianp** [comment]
@donutsteele yes, it's still open

**Comment by kjschmidt913** [comment]
I see this is still open- is anyone working on it or could I?

**Comment by christianp** [comment]
@kjschmidt913 thanks for offering - go ahead. Please have a look at our [guidelines on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code) first, and make a pull request when you've got something we can look at.

**Comment by kjschmidt913** [comment]
@christianp great! Will do
