### ISSUE TITLE
The "submit part" button shouldn't be hidden

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#523]
The "submit part" button hides itself when the part is not dirty, as a hint that nothing will change when you submit.

This makes it impossible to submit "empty" answers which don't involve changing the initial state of the input widget - for example, an empty string or selecting none of the available choices. With the new custom part types, these become valid answers.

The "submit part" button should always be visible, and enabled. The student will get feedback if their answer can't be submitted, anyway.

**Comment by ryan-barrett** [comment]
Hi, can I work on this?

**Comment by christianp** [comment]
Hi @ryan-barrett , sorry for the slow reply - I've been on strike and then on annual leave. 
Please do have a go at this and submit a pull request when you've got something I can look at.
