### ISSUE TITLE
Option to not show numberentry fraction input hint.

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#526]
There's an option `showPrecisionHint` for when there's a precision restriction. It should also be possible to ask for the fraction input hint not to be displayed.
Requested by Johan Maertens.

To do this: 
- add another option `showFractionHint` in `runtime/scripts/part/numberentry.js`, basically copying the code for `showPrecisionHint`.
- do the same in `themes/default/files/scripts/parts/numberentry-display.js`
- use the setting to decide whether to show the hint in `themes/default/templates/xslt/parts/numberentry.xslt`.
- add the option to the editor.

**Comment by KookyLukey** [comment]
Hey, I would like to have a go at this one. I think I have a pretty good idea of what to do from your description. This will be my first time actually contributing to something open source, but seems like a cool project and good way to start being a regular contributor.

**Comment by christianp** [comment]
@KookyLukey thanks for offering! Submit a pull request as soon as you've got something.

**Comment by paplio** [comment]
Hi! I noticed this is still open. Is there any chance I can get to work on it?
