### ISSUE TITLE
Use ES6 features / drop IE11 support

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#527]
I'd like to start updating the code base to use the newer ES6 features, which will make everything a lot tidier and less complicated.
Firefox and Chrome have supported ES6 classes since early 2016, and are usually kept up to date. The only holdout is IE11, which hasn't been updated since 2013 since MS would prefer you use Edge.
However, our campus PCs still default to IE11, and RAS runs Windows Server 6.3, which doesn't have Edge.

So I don't think we canstart using ES6 yet, without using something like [Babel](https://babeljs.io/) to transpile, which I don't want to do.

**Comment by ManuelBlanc** [comment]
> [...] using something like Babel to transpile, which I don't want to do.

Would you mind elaborating why?

**Comment by christianp** [comment]
> Would you mind elaborating why?

Because it adds another layer of things to install.

**Comment by christianp** [comment]
We've decided that we will use features when they have more than 95% support on caniuse.com.
