### ISSUE TITLE
Matrix entry with fractions failing

### ISSUE THREAD

**Issue by Tandethsquire** [numbas/Numbas#555]
As in the MWE here: https://numbas.mathcentre.ac.uk/question/34818/minimal-working-example-fractional-matrices/

Despite the "Allow student to enter fractions" option being ticked, upon submission of an answer for part (b) with fractions in it, student is faced with "Cannot submit answer; check for errors". Will accept and correctly mark if, eg, 0.5 is entered instead of 1/2. Is this a bug, or has the means by which we mark matrices that include fractions moved to the new marking features of NUMBAS v3.0?

My current workaround is, for example, https://numbas.mathcentre.ac.uk/question/34283/simplex-method/ part (b), using a custom JS marking script, but I'm aware this is neither elegant nor in the spirit of the update!

P.S. Apologies for laxity of commenting in variables and/or JS code in my questions.

**Comment by christianp** [comment]
I've fixed this in f85d0a4dc6e6831b1e5f37941e0bd24b3a2ced6e. 
I had indeed forgotten to put the fraction stuff in the new marking algorithm, so I've now put that in, and while I was there I did some more work to match the way number entry parts now behave with respect to precision restrictions.

Thanks for pointing this out, and for the very helpful example.
