### ISSUE TITLE
"all-or-nothing" marking for "choose several" part

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#561]
You might want to award marks only if the student ticks exactly the right set of choices, and give 0 marks for any other selection.

I've made [an example with a custom marking algorithm](https://numbas.mathcentre.ac.uk/question/35837/award-marks-only-if-all-correct-choices-are-ticked).

**Comment by rlowman** [comment]
I would like to work on this if that is ok.

**Comment by christianp** [comment]
@rlowman Sure - send a pull request when you've got something. Feel free to ask for help if something's not clear.

**Comment by EVratsanou** [comment]
Hi,I would like to work on this issue

**Comment by christianp** [comment]
@EVratsanou thanks! Please have a look at [our guidelines on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code)

**Comment by calvinm4** [comment]
Myself and two others would like to start contributing to the project and thought this may be a good place to start. Is this still a feature that you would like to be added? If so, could you point us in the right direction?
