### ISSUE TITLE
'Quantity with units' question type doesn't work in 'Gap fill'

### ISSUE THREAD

**Issue by Yatesj** [numbas/Numbas#568]
When using a 'quantity with units' as a gap fill you get the following error:

"There was an error in this part's marking algorithm. Please report this. Error evaluating note <code>marked_original_order</code> - Error evaluating variable marked_original_order: Cannot read property 'contains' of undefined"

**Comment by christianp** [comment]
This is a consequence of #569, so I'll close this issue and deal with the problem there.
