### ISSUE TITLE
'Quantity with units' produces confusing error codes for students

### ISSUE THREAD

**Issue by Yatesj** [numbas/Numbas#569]
When answering the 'Quantity with units' question type you receive error messages that could be confusing to students. For example when entering only the units (without a number before it) or when entering units that aren't supported or don't exist you are given the following error message:

> Error evaluating variable mark: Variable <code>close_enough</code> is not defined.

An example of when this might occur: A student types in '5 Nm' instead of the correct answer '5 N m' or '5 N*m'. This leads them to believe the mistake lies with the question author and not themselves and could deter them from completeing the question.

**Comment by christianp** [comment]
I've seen this too. I'll try to sort it out.
Thanks for the report!
