### ISSUE TITLE
Hide the submit part button when there's only one part

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#573]

**Comment by apallennz** [comment]
Hi, I've been looking at http://numbas.github.io/editor/ubuntu-local.html in terms of getting the Numbas software generally working

In the following section
Configuration
Run
python first_setup.py

Having followed all previous instructions, running _python first_setup.py_ just says the file isn't found
ideas?

**Comment by christianp** [comment]
@apallennz are you in the right directory? After running `git clone`, you'll need to change into the numbas editor directory with `cd numbas_editor`.

**Comment by apallennz** [comment]
pwd
/home/<username>/Downloads/numbas_editor

python first_setup.py
python: can't open file 'first_setup.py': [Errno 2] No such file or directory

**Comment by christianp** [comment]
Have a look with your file manager to check that you're in the right place and you've cloned the repository fully.

**Comment by apallennz** [comment]
I only cloned the repo again in the last couple of days

~/Downloads/numbas_editor$ ls
bin              docs.md     locales          README.md         scormfiles
CONTRIBUTORS.md  extensions  Makefile         requirements.txt  tests
docs             jsdoc.conf  marking_scripts  runtime           themes

there isn't actually a first_setup.py file in the repo from what i can see?

~/Downloads/numbas_editor$ find -maxdepth 5 -type f -name *.py
./bin/html2textile.py
./bin/migrations.py
./bin/htmlescapes.py
./bin/xml2js.py
./bin/numbas.py
./bin/numbasobject.py
./bin/examparser.py
./bin/exam.py

**Comment by christianp** [comment]
That's the Numbas runtime repository. You also need to clone the editor repository.

**Comment by apallennz** [comment]
i don't mean to tell you you're wrong, but see the path before 'ls', i've run ls on the editor repo

**Comment by christianp** [comment]
Those are exactly the files in the Numbas repository

**Comment by apallennz** [comment]
i **just** realized the mistake i've been making, it'll probably work now :)

**Comment by apallennz** [comment]
so trying to run the following commands
pip3 install -r numbas_editor/requirements.txt
pip3 install -r numbas_runtime/requirements.txt

i always get
- Failed building wheel for Pillow
and
- Command "/home/<username>/Downloads/numbas_venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9vs2qmj8/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d0ujye8a/install-record.txt --single-version-externally-managed --compile --install-headers /home/<username>/Downloads/numbas_venv/include/site/python3.6/Pillow" failed with error code 1 in /tmp/pip-install-9vs2qmj8/Pillow/

**Comment by apallennz** [comment]
any comments on the above?

**Comment by christianp** [comment]
@apallennz You might need to install the dev dependencies for Pillow. See https://pillow.readthedocs.io/en/5.3.x/installation.html#building-on-linux for some instructions.
pip should be trying to install the prepared wheel package, rather than building it locally. Are you running inside a virtual machine? Either way, if you can decipher the filenames at https://pypi.org/project/Pillow/#files to find a file that matches your architecture, OS and Python version, you could try installing that directly.

Sorry this is so complicated - Python packaging can sometimes get unreasonably complicated.
