### ISSUE TITLE
Add "show correct answer on reveal?" option to custom part types

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#577]
The built-in part types have an option "Show correct answer on reveal?"

Custom part types should have that, too.

**Comment by InimitableArtist** [comment]
Is this solved? I would like to take this if it isn't.

**Comment by christianp** [comment]
It's still open. Thanks for offering. Please have a look at our [guidelines for contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code)

**Comment by InimitableArtist** [comment]
Okay great, I'll get on it.

**Comment by paplio** [comment]
Hello! I noticed this issue is still open. I haven't contributed to open source before, but I think I understand this issue and can work on it. Can I submit a PR?
