### ISSUE TITLE
Steps with one part have no submit part button

### ISSUE THREAD

**Issue by JoshuaCapel** [numbas/Numbas#586]
Unfortunately steps with only one part have no submit button. This means students have difficultly submitted these single steps.

I believe this a side effect of a recent commit that removed it from questions that only had one part.

https://github.com/numbas/Numbas/commit/e96ebcfd2d142cb6b16365375d4f35e98d4286e2

**Comment by JoshuaCapel** [comment]
I have made a pull request that should fix this issue: https://github.com/numbas/Numbas/pull/587/commits/a36402eac4a6cd6b57eee72a1a4a0b7ccb1f2ab7

**Comment by christianp** [comment]
Thanks for reporting this. I've written a slightly more robust query (I think) which fixes this, so I'll close your PR.
