### ISSUE TITLE
Matrix entry with custom marking

### ISSUE THREAD

**Issue by Tandethsquire** [numbas/Numbas#588]
On creating a matrix entry part to a question, if one tries to extend the base marking algorithm an error shows above the unit tests saying "Error marking: There was an error in this part's marking algorithm. Please report this. Numbas.jme.evaluate must be given a Scope". As a result, the answers are no longer marked as correct but no error (of the form above) is shown. I haven't been able to find a way to make this work even if I replace, rather than extend, the base marking algorithm.

MWE (obviously not the question I've got planned!) here: https://numbas.mathcentre.ac.uk/question/share/view/79393b08-8efa-43b2-99ad-3defa86be96f

Removing the custom marking makes the question behave as expected.

**Comment by christianp** [comment]
You didn't even need to make a custom marking algorithm. This bug was introduced when I added a 'scope' parameter to the part marking function. Thanks for reporting it!
Fixed by numbas/editor@2a1d25be3bd601ed2cdfe9f66d41edccb705a903
