### ISSUE TITLE
FYI: Numbas in docker

### ISSUE THREAD

**Issue by Zhiz0id** [numbas/Numbas#596]
FYI
I've created repository with Dockerfile and stack.yml which helps run Numbas as standalone app local or in cloud.

https://github.com/Zhiz0id/Numbas-docker

**Comment by christianp** [comment]
That's great, thanks! Could you add a licence to it? It would be easiest for us if you used the Apache 2.0 licence.

**Comment by Zhiz0id** [comment]
License added.

**Comment by christianp** [comment]
I've forked this at [numbas/numbas-editor-docker](https://github.com/numbas/numbas-editor-docker). Thanks for starting it off - I've been meaning to look at Docker for a long time!
