### ISSUE TITLE
Gapfill Marking Algorithm Issue

### ISSUE THREAD

**Issue by Tandethsquire** [numbas/Numbas#603]
If a gapfill question has a mathematical expression as a gap, there seems to be an error thrown in any sort of use of marking algorithms. As a MWE, take a gapfill part with a single 'expression' gap: entering any expression (before writing any custom marking algorithm or even ticking the 'use custom marking algorithm?' boxes) into the 'Student's answer' box in the 'Marking algorithm' tab throws a error in the browser console:
"Numbas Error: Can't texify token type ↵    at jme.display.treeToJME".
See image below for a demonstration of this behaviour.
In practice, this seems to stops the definition and evaluation of any custom marking notes. When the aim is to have a two-gap question marked entirely by a custom marking algorithm on the overarching gapfill part, this is somewhat problematic..
![screenshot from 2019-03-06 12-10-34](https://user-images.githubusercontent.com/14112279/53880451-e953a580-4008-11e9-8fb4-2dc9d33b3bad.png)

**Comment by christianp** [comment]
Thanks for reporting this. I think I've fixed it - please take a look and close this issue if so.

**Comment by Tandethsquire** [comment]
That has done the job! Thanks.
