### ISSUE TITLE
Marking Error (could be programming, but I can't seem to find it)

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#612]
In "Entropy generation through a wall", Part(a)Step(1) and Part(b)Step(2) are programmatically equivalent (outside of a minus sign and pulling from a different variable), but when I try to evaluate the submissions, Step(1) is marked wrong but Step 2 seems correct.

**Comment by christianp** [comment]
That question now seems to only have one part. Did you fix the problem?

**Comment by gordonsmithwkuedu** [comment]
Sorry, made a typo...

Step(1) and Step(2)

**Comment by christianp** [comment]
There was a bug in the marking algorithm: the margin of error in your second part is a negative number, and the marking algorithm wasn't taking the absolute value, so the minimum and maximum allowed values were the wrong way round. 
I've made it take the absolute value of the margin of error. Please check the question and close this issue if it's fixed

**Comment by gordonsmithwkuedu** [comment]
Seems to be good now.  Thanks!
