### ISSUE TITLE
Gapfill issues

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#621]
I'm playing with using gapfill as fill-in-the-blank problems.  I'm seeing something odd...

What I did:
set up a two-part problem, each part  with a single gapfill call.  The first gapfill was identified as [[0]] and the second was identified as [[1]].  The gaps themselves were appropriately numbered as 0 and 1.

What I got:
a compile error "Compilation error: Error constructing exam: Reference to an undefined gap in a gapfill part (2,1)"

I think what's going on is that the system rigidly defines gaps within a part as 0..1..2.., and starting with 1 confuses it.  It understands its looking for a gap, looks for gap 0, and when it doesn't find it, it explodes.   I don't get the error if I create the gapfill as a single question of only 1 part, naming the gap as 0, which is my current workaround.  Can you confirm this interpretation?

Reading the documentation, I got the impression I could name a gap anything I wanted, and call it appropriately.  If my interpretation is right, it seems I have to be more careful in how I name things.

**Comment by christianp** [comment]
Can you give me a link to a question, or a .exam file, which produces this error?

**Comment by christianp** [comment]
I think this misunderstanding is fixed by the new gap dialog.
