### ISSUE TITLE
Save the random seed in the SCORM suspend data

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#634]
`Numbas.exam.seed` is the seed for the random number generator, and is displayed on the results screen as "session ID". The idea was that you could use the session ID to regenerate an exam with exactly the same randomisation, without relying on having a saved SCORM attempt.

Students are advised to take screenshots of the results screen. It would be good if we could use the session ID to verify that a screenshot is of the attempt the student claims it is.

So, `Numbas.exam.seed` should be saved in the suspend data, and loaded when resuming an attempt. The current state of the random number generator could also be saved, but it should only be restored once the whole attempt is finished loading - you can't rely on exactly the same calls to the RNG happening in the same order.

**Comment by ApoorvChandurkar** [comment]
Hey, I wanted to contribute to numbas and work on this ticket, I am a newbie in Django though, can you point me where to start?

**Comment by christianp** [comment]
@ApoorvChandurkar thanks for offering to help. This issue won't affect any parts of the editor, which uses Django: it's purely about the runtime, which is written in JavaScript.

The bit of code that needs to be changed is [setSuspendData in scorm-storage.js](https://github.com/numbas/Numbas/blob/master/runtime/scripts/scorm-storage.js#L239). The variable `eobj` should have a key `randomSeed` whose value is `exam.seed`
