### ISSUE TITLE
Entering a list of answers without requiring a necessary order

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#635]
I am writing a dynamics problem (Translational Kinematics Question)  concerning 2D kinematic motion, and as part of the steps I have students enter the two components of the acceleration.  Such a problem can be approached in a variety of coordinate systems, depending on the circumstances.  Right now, the students are posed with a variety of steps:

1) Choose the appropriate coordinate system (polar, in this case)
2) Choose the appropriate forms for the problem (selecting from velocity and acceleration in all relevant coordinate systems so the answer to 1) isn't given away)
3) Determining the appropriate time for the position to be evaluated

and now we get to components.  As currently approached, I have to reveal that the correct choice for 1) was polar, since I'd be asking for radial and angular components as two separate steps (instead of x/y, or n/t).  And since they see all steps simultaneously, knowing 1) makes 2) and 3) much easier.  Would it be possible to require they answer both parts in a single question?  If so, then I can preserve the veil by not "naming" the directions, but it would require a means of entering two numbers without requiring a "correct" order (i.e., {radial, angular} or {angular, radial}. Same numbers, different order...

**Comment by christianp** [comment]
At the moment I'm working on something for exactly this kind of scenario! It's going to take a long time to finish, so I wouldn't recommend waiting for it.

Right now, you could do something clever with marking algorithms and adaptive marking: have two gapfills, corresponding to two components, and set the correct answers based on what the student chose in the first step. 

You could use the [sort student's answers before marking](https://docs.numbas.org.uk/en/latest/question/parts/gapfill.html#term-sort-student-s-answers-before-marking) option to allow them to enter the components in either order, or you could write some text along the lines of "enter your answer in the form radial-angular, x-y, or n-t, according to your choice in step 1".

**Comment by gordonsmithwkuedu** [comment]
Sounds good!  I'll look forward to seeing your solution, and will try your recommendations going forward!
