### ISSUE TITLE
German locale:  question.score feedback.score total actual not showing correctly

### ISSUE THREAD

**Issue by bhellmark** [numbas/Numbas#636]
As the title suggest, the translation for "question.score feedback.score total actual" not showing is not showing correcly, ist is simply shown as **question.score feedback.score total actual** instead of the correct translation "Punktestand: {{score,niceNumber}}/{{marks,niceNumber}}".

To reproduce this error simply switch to German language on your profile page an start a new editing a new question and then switch to the preview.

**Comment by christianp** [comment]
Thanks for reporting this. I split the score feedback into two separate strings in Numbas v4, so the locale files needed to be updated. I've manually fixed the ones that I feel confident with, including German.
If you have the time, please help to complete the German translation at [poeditor](https://poeditor.com/join/project/4yrwn1Nc2l)

**Comment by bhellmark** [comment]
Thanks, it's indeed fixed now.

> If you have the time, please help to complete the German translation at [poeditor](https://poeditor.com/join/project/4yrwn1Nc2l)

Should be pretty much complete now, unsure about some translations (mainly "note" (EN) as "Notiz" (DE)), marked those as fuzzy.

**Comment by christianp** [comment]
Thanks!
