### ISSUE TITLE
Privacy Settings

### ISSUE THREAD

**Issue by gordonsmithwkuedu** [numbas/Numbas#637]
I'm still wrapping my head around it, but I'm curious about a potential drawback to the "wholly-open" approach to NUMBAS.  When applied as marketed (a tool for mathematics), and for as long as it's been around, I can easily see that it would be beneficial for users to find examples, and potentially hard for students to locate a particular problem used by a particular professor.

In my case, however, I'm bending the use slightly by applying this great tool in engineering courses, and so the relevant pool is much smaller.  I'm not saying our students would create a NUMBAS account, and then search for all problems authored by me, or all problems dealing with a particular subject, but the fact that it's possible means that I should think about that possibility.

I'm thinking the "correct" solution is to self-host a NUMBAS server that I only share with other professors, and not do development on the public site, but I also wanted to confirm that there are no privacy settings I can apply on the public server?

**Comment by christianp** [comment]
Did I answer your question? If so, please close this issue.
