### ISSUE TITLE
Order of terms in polynomials

### ISSUE THREAD

**Issue by BillFoster** [numbas/Numbas#65]
There is a problem in using jme code for displaying polynomials. In many cases a poly should be displayed in some order e.g. ascending order -.see questions such as testing\1041cba2_4.exam. There is at present no control using jme and forcing the order using latex can be messy.

**Comment by christianp** [comment]
Removing the "custom marking algorithms" milestone because this is really about a simplification rule.

**Comment by christianp** [comment]
Fixed in numbas v4.0.
