### ISSUE TITLE
Complex number arithmetics

### ISSUE THREAD

**Issue by zaript** [numbas/Numbas#651]
In the
 https://numbas.mathcentre.ac.uk/question/11785/arithmetics-of-complex-numbers-ii/
part A seem to be bugged in some cases:

for 4i*(-7+7i) revealed answer is -28 - - 28i, and the correct answer is not accepted.

**Comment by christianp** [comment]
Thanks for reporting this. It was fixed in commit 29e98f4717b7fe62feaa2828ab48a8669e4e1019
