### ISSUE TITLE
Warning messages are not displayed in some circumstances

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#658]
Two slightly different but related scenarios when warning messages, such as for input
`xcosh(x)`
do not display:

1. The warning message is displayed if the student presses the return key after answering, but not if the student clicks on the Submit button. If feedback is turned off then, unless they put focus back in the input box, they would not get any indication of a problem until they review their attempt.

2. This compounds 1. If the student types `xcosh` and pauses, they see an invalid expression warning, but if they continue to `xcosh(` they then see the latest warning, about a missing bracket, until they complete the expression. Once the expression is complete they do not see the invalid expression warning again, unless they submit using the return key as per 1. Obviously a fix for 1. would make this less important.

**Comment by christianp** [comment]
I don't have a solution for this. Maybe warning messages should be shown in the feedback area, even if feedback is turned off? I can see that going wrong with gap-fills. 

The reason the box disappears is that it overlaps other content. It's not great for accessibility, but I don't have a better solution.

Your point 2 isn't quite right - you only get a warning on typing `xcosh` if you've got "warn if student uses unexpected variable name" turned on. The bad function name warning isn't part of that. Maybe it should be.

**Comment by christianp** [comment]
I've changed the behaviour when "show answer state" is turned off, to always show feedback lines about invalid answers. I think that resolves this.
