### ISSUE TITLE
Pattern-matching quirk for terms with coefficient -1 

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#660]
I spotted this in a similar question to the pattern matching demo at
https://numbas.mathcentre.ac.uk/question/44548/demo-of-pattern-to-match-restriction/

In (k) in the above link an answer like
`1 + x - (4/2)*x^2 - (1/6)*x^3 + (16/24)*x^4`
passes the restriction, but not
`1 + x - (4/2)*x^2 - x^3 + (16/24)*x^4`

I have a simpler version here: https://numbas.mathcentre.ac.uk/question/52619/pattern-matching-issue/ which demonstrates the same issue with the restriction ``` `+-(integer:$n `: 1) x^2 ```

**Comment by christianp** [comment]
You need to make the coefficient optional. In your simple example, this pattern matches everything you want:

```
`+- (integer:$n`? * x^2)
```
