### ISSUE TITLE
Possibility to use ¬ in formulas

### ISSUE THREAD

**Issue by ugonj** [numbas/Numbas#661]
When entering formulas it is possible to use other boolean operators like ∧and ∨using the appropriate unicode characters. The system does not recognise ¬. It would be nice if it did.

To "reproduce":
1) Enter  "p ∨ (p ∧ p)" in a formula box. The formula is correctly interpreted;
2) Enter  "¬p ∨ (p ∧ p)" in a formula box. The formula is rejected.

Other Unicode symbols that might be useful to recognize are →and ⊕.

**Comment by christianp** [comment]
Good suggestion, thanks!
