### ISSUE TITLE
Translated Numbas to simplified chinese.

### ISSUE THREAD

**Issue by liehtt** [numbas/Numbas#676]
This is my first time contributing to an open source repo. Forgive me if I did something wrong. 

I have translated Numbas into simplified chinese. 

How do I add the json file?

**Comment by christianp** [comment]
Thank you very much for this translation! I've exported the translation from POEditor into the Numbas repository, and it's now available through the Numbas editor.

If you have any suggestions for changes to the layout of the interface in Chinese, please create new issues here.
