### ISSUE TITLE
empty selection in list selection: can't reveal answer

### ISSUE THREAD

**Issue by ugonj** [numbas/Numbas#678]
### Summary

If a question part has a "choose one from a list" gap, and the answer is submitted without this gap being answered (no choice is made), this causes a bug when revealing answers. In particular, this makes exams containing the question crash.

### To reproduce

To reproduce: 
1) Create a question with a single part, and a single gap ("choose one from a list")
2) Include the question in an exam
3) Run the exam, submit the question and end exam
The error message "TypeError: ticks[i] is undefined" is displayed.

The problem seems to be on line 29597 of scripts.js (as of writing this report). Changing the line from:
``` if(ticks[i][0])```
to 
``` if(ticks[i] && ticks[i][0])```
appears to fix the issue.

### Link

Here's an exam reproducing the problem:
https://numbas.mathcentre.ac.uk/exam/13442/choose-one-from-a-list-and-ticks-i/

### Real use issue:

I have a question with multiple choice gaps, which should be left blank depending on answers to other gaps. This causes those questions to crash.

**Comment by christianp** [comment]
Thanks for reporting this. It's a recently-introduced bug: I didn't test a multiple choice part inside a gap-fill when I made a change recently. It should be fixed now; please let me know if you have any more problems.
