### ISSUE TITLE
Showing steps should disable answering the full part question 

### ISSUE THREAD

**Issue by davidhadas** [numbas/Numbas#681]
When responding to an part, after responding to steps, the resulting text is confusing (code should allow responding to the full part if steps were already opened....)

![image](https://user-images.githubusercontent.com/4232801/79381953-6d49c200-7f6b-11ea-8de0-5ca1a9fa44fd.png)

**Comment by christianp** [comment]
I'm not sure which bit of this you think should change. Could you give a suggested alternate text?

**Comment by davidhadas** [comment]
I guess different exams use steps in a different way. 
One way to use steps is to prove a step by step solution and allow the student perform those steps and collect some of the mark. 
When the student than open the step-by-step option (and follow it, and collect marks using it), he/she should not be allowed to press submit part any more. This button should be disabled. 
Hence the text "Your answer is correct... counted" should also never appear (since the user should not be allowed to press submit part any more)

At least, this is my understanding of teh situation that occurs when step-by-step is used.

**Comment by christianp** [comment]
That's not how steps are intended to be used.
