### ISSUE TITLE
Question content sometimes won't allow scroll 

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#683]
I've so far only been able to replicate this in one exam: https://numbas-editor.mas.ncl.ac.uk/exam/540/mas1403-specimen-exam/. It seems to be a Safari issue. 

That exam has an error in the console: "jme.shunt.keypair in wrong place". It's not clear if that is related.

**Comment by christianp** [comment]
I think the keypair problem is unrelated, but I've fixed it anyway. There was an SVG with a `<style>` tag which Numbas was trying to sub variables into.

**Comment by christianp** [comment]
I've tried that exam (now at https://numbas.mathcentre.ac.uk/exam/16816/mas1403-specimen-exam/) in Safari 15.1 and the question content scrolled properly, so either Safari fixed a bug or I did.
