### ISSUE TITLE
Partial feedback messages appear in review mode when all feedback is turned off.

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#685]
With all feedback hidden from students, including "Show score feedback icon?" unticked on question parts, some feedback messages still appear in review mode:

![image](https://user-images.githubusercontent.com/15893967/81283724-fe84f380-9054-11ea-804e-7cbcd510eb86.png)

In addition, in the example above, part a) has a warning message associated with a pattern matching restriction, which is not prefixed to "1 mark was taken away".

**Comment by christianp** [comment]
Where is the question?

**Comment by chrismgraham** [comment]
Oh, sorry, here it is: https://numbas.mathcentre.ac.uk/exam/14140/feedback-messages-in-review-mode/

**Comment by christianp** [comment]
The reason this shows up is that you've got "show score feedback icon" turned off for the mathematical expression gap, but not for the parent gap-fill part.

It looks like the gap-fill marking algorithm strips messages out of feedback items from gaps if they have "show feedback icon" turned off. That explains where the pattern message went, but what's left doesn't exactly look sensible. I'm not sure how else to square "don't give feedback for the gap, but do for the parent gap-fill" though - you're saying you want to account for the marks in the parent part, but not show any detailed feedback? Maybe all the items should be squashed into one "you got this many marks" item.

**Comment by christianp** [comment]
Or maybe the "show score feedback icon" setting shouldn't be available for gaps, only top-level parts.

**Comment by chrismgraham** [comment]
Oh, I see! Not certain, but I think where adaptive marking has been used for labs you would need the control at gap level?

**Comment by christianp** [comment]
Can you give an example

**Comment by chrismgraham** [comment]
https://numbas.mathcentre.ac.uk/exam/12090/eng1002-lab-guide-1-truss/

**Comment by christianp** [comment]
Got it - you don't want a feedback icon for gaps representing measurements, where there's no correct answer.

(The other option is that you set the gap up to mark any acceptable value as correct)

**Comment by christianp** [comment]
I've just had a go at that truss calculation question. The gaps in the first column with no correct answer don't appear in the feedback at all, which I think is correct (though maybe in an ideal world we'd have a line saying something like "your answer is acceptable")

I think given that there are ways of getting what you want, it's not worth the risk of trying to do something clever with feedback items, like merging adjacent items with no message.
