### ISSUE TITLE
Advice per part

### ISSUE THREAD

**Issue by RuthHand** [numbas/Numbas#702]
Hi. I am not sure if this is possible or not.  When working in Explore mode, it would be helpful for the part-level advice to be available after each part, rather than only at the end of the whole question.

**Comment by christianp** [comment]
What use case do you have in mind?

Could you make an information part with the advice, and make that a "next part"? If you lock the part the advice is about, you'd get the same behaviour as "reveal answers" for a whole question.

**Comment by RuthHand** [comment]
That is genius, thank you, I think that will work and I will have a play now

**Comment by christianp** [comment]
Great! Please close this issue when you've got a solution.

**Comment by RuthHand** [comment]
It works!  It isn't quite as 'slick' but certainly performs the function. Thanks for your help.
