### ISSUE TITLE
'locked' parts unlock

### ISSUE THREAD

**Issue by RuthHand** [numbas/Numbas#703]
In Explore mode.

Part A 
Lock this part
Next part B

Part B
Next part A

A is now unlocked

An obvious fix is to remove the loop!  But.....in reality because i want more parts with more interconnections this isn't feasible

**Comment by christianp** [comment]
The parts you create in the question editor are *templates* of parts. When the student clicks on a "next part" option, it creates a new instance of that part. So in your example, there are two instances of part A.
The reason for this is so you can have questions where you loop back to the same position but with different conditions.

I think what you want to do is to not have a "next part" link from part B, but instead to tick the "suggest going back" option - that will send the student back to the original instance of part A, which remains locked.

**Comment by RuthHand** [comment]
Thanks so much Christian, that makes sense.  I think I need to investigate the way the conditions work.
