### ISSUE TITLE
Very odd JME bug(s), produces pi from nothing

### ISSUE THREAD

**Issue by 0-andy-0** [numbas/Numbas#704]
Just narrowing down a bug we found a Gaussian algorithm question, it turns out that

`vector(3)-9*(11*vector(1/33))`

displays 

`( 0 * pi π )`

vector(3)-11*(9*vector(1/33)) is correct though.

[Link to question for Numbas admin](https://numbas.mathcentre.ac.uk/question/66059/2-line-bug/)

**Comment by christianp** [comment]
Thanks for reporting this. Fixed by commit 183ae8ff5bde371cc02ffd2699c513f5e82947a6.
