### ISSUE TITLE
random(range) should return integer instead of number when appropriate

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#717]
`random(1..10)` produces a `number` value, not an `integer` as you might expect.

**Comment by Shiv1202** [comment]
Hey @christianp where I find the files related to this issue.

**Comment by christianp** [comment]
Hi @Shiv1202, thanks for offering to help. This issue is actually fixed now, I just forgot to close it. Have a look at [the issues labelled "good first issue"](https://github.com/numbas/Numbas/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for something to get started on.
