### ISSUE TITLE
The marking algorithm `apply` function could take multiple notes

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#725]
The mark note for algiorithms often looks like this:

```
apply(note1);
apply(note2);
apply(note3);
...
```

It would be more convenient to write

```
apply(note1, note2, note3, ...)
```

**Comment by ankushduacodes** [comment]
i would i like to tackle this issue but its my first time contributing to an open source project... 
if you could provide any helping tips for what is issue is about and where to look for, i would really appreciate that

**Comment by christianp** [comment]
@ankushduacodes thanks for offering to help! First of all, please set up a Numbas development environment. See our guide about that: https://www.numbas.org.uk/contributing-to-numbas/#contributing-code

This issue is to do with custom marking algorithms ([docs](https://docs.numbas.org.uk/en/latest/marking-algorithm.html)). The function `apply`, defined in [runtime/scripts/marking.js](https://github.com/numbas/Numbas/blob/master/runtime/scripts/marking.js#L230), should take multiple arguments rather than just one. The [`product`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/jme-builtins.js#L1410) function is an example of how to accept multiple arguments.

**Comment by ankushduacodes** [comment]
@christianp Thanks for the help! I have set up virtual env for Numbas development according to the guide provided.
but I could not figure out mac configuration
when i run `python3 first_setup.py` in the numbas_runtime directory, it says there is no file or directory by name
<img width="1024" alt="Screenshot 2020-08-08 at 10 52 59 AM" src="https://user-images.githubusercontent.com/61025943/89703381-b7661180-d967-11ea-8146-c0f1ef6677e4.png">

**Comment by ankushduacodes** [comment]
I still cant figure out how to configure my mac to work with numbas_runtime, any suggestion on above?

**Comment by christianp** [comment]
@ankushduacodes `first_setup.py` is in the editor directory.

**Comment by webbdays** [comment]
@christianp 
I want to work on this.

**Comment by webbdays** [comment]
Are there anyone working on this ?

**Comment by christianp** [comment]
@webbdays thanks for offering to help. You can assume that all issues labelled "good first issue" are OK for you to just start working on.
