### ISSUE TITLE
Check that javascript marking scripts work inside gap-fills

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#726]

**Comment by georgestagg** [comment]
These do seem to be broken. Adding a custom javascript marking script to a mathematical expression gap in a gap fill part generates the error:
```
Error marking named gap: undefined is not an object (evaluating 'part.finalised_result.states')
```
when an answer is submitted.

**Comment by christianp** [comment]
Actually, I was wrong: I'd already decided what to do! The code at `Part.setScript` already does what I described, it was just returning the wrong sort of object.

And in fact, it's occurred to me that a custom JS marking script should overwrite `Part.mark_answer` rather than `Part.mark`, since that's the bottom of the long ladder of marking methods. So I've made that change, and now I just need to document what a marking script should return.
