### ISSUE TITLE
A trailing comma in a dictionary gets "Can't parse list: mix of dictionary and list elements"

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#727]

**Comment by webbdays** [comment]
I want to work on this.
Can you please refer where this problem occurs ?

**Comment by christianp** [comment]
@webbdays thanks for offering to help, but fixing this will involve some tricky work with the parser, so I'd like to do it myself. You could look at [the issues labelled "good first issue"](https://github.com/numbas/Numbas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to find something easy to start with.

**Comment by webbdays** [comment]
Ok

**Comment by christianp** [comment]
Actually, having tried this, I can't reproduce it! `["a": 1, "b": 2,]` works fine.

**Comment by christianp** [comment]
I can reproduce it! 

```
q(1,["a": 1,])
```

It looks like a dictionary with a trailing comma as the second argument to a function causes the error message.
