### ISSUE TITLE
Only the last instance of an HTML node jme variable is visible

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#731]
When using a jme variable that is an HTML node, set up with e.g. html('<div>Text!</div>'), if the variable is used more than once, the node is only visible in the last instance. For example, if used in a statement and part prompt it will only appear in the latter, and if used in choices for an MCQ question, the variable only appears in the expected answers.

**Comment by christianp** [comment]
I think this just needs to be documented, or it should throw an error on subsequent use.

**Comment by christianp** [comment]
This is a duplicate of #886
