### ISSUE TITLE
Uploading Themes

### ISSUE THREAD

**Issue by ccscaiado** [numbas/Numbas#735]
Hi Christian,

It looks like email isn't an option at the moment, I think both Universities have blocked email traffic due to the current cyber attacks.
I have another problem that I was trying to resolve by creating a local installation but without being able to add extensions, I’m a bit lost.
My old theme doesn’t work with the latest update and I can’t upload a new theme via the NUMBAS main website, I get the message

“Server Error
Something's gone wrong. Sorry about that.
If you've got the time, please email numbas@ncl.ac.uk with a description of what you were trying to do.”

I also can't email a ncl.ac.uk until security issues are resolved.
Could you please help me resolve the theme uploading issue? The current themes have very wide margins and are messing up with the display of some questions.

**Comment by ugoertz** [comment]
See https://github.com/numbas/editor/issues/535 for some comments on this, and a suggestion how this could be fixed in a locally installed instance of the Numbas editor. (At least, the fix appears to work for me.)

**Comment by christianp** [comment]
This is now fixed. Thanks for your patience.
