### ISSUE TITLE
Mass remark feature

### ISSUE THREAD

**Issue by CWCleghornAI** [numbas/Numbas#737]
Apologies if this is the incorrect place to post.

Often times an error in the memo answer is only spotted after the test is finished. It would be great if a remark across all submissions could be triggered with the corrected memo.

If this does exist I could not find it.

**Comment by christianp** [comment]
Version 2.9 of the Numbas LTI tool now includes a "Remark" tab which tries to automatically remark all attempts at a resource, and can save changed scores to the database. There's [some documentation on how this works](https://numbas-lti-provider.readthedocs.io/en/latest/instructor/resources.html#remark).
