### ISSUE TITLE
Remove "Print your exam transcript" in Performance Summary for exams

### ISSUE THREAD

**Issue by ItsClaudiPie** [numbas/Numbas#747]
![image](https://user-images.githubusercontent.com/45623055/96472326-a28fdf00-1230-11eb-8405-63da3241905d.png)

Hi,

Can someone help adding an exam theme to remove this option? That would be great! 

Kind regards
Claudia

**Comment by christianp** [comment]
Hi Claudia, I've got an issue at #746 about adding an option to turn this button off. I'm going to add that option today.

**Comment by ItsClaudiPie** [comment]
Hi Christian

Thank you for being awesome!

Kind regards
Claudia

Claudia

**Comment by ItsClaudiPie** [comment]
Thank you for being awesome!
