### ISSUE TITLE
Student answers not visible after pause/resume

### ISSUE THREAD

**Issue by rogueosb** [numbas/Numbas#750]
When a student submits answers to an exam, pauses the exam, _closes_ the window, and returns to the exam, they are unable to view their saved answers. Example shown here:

![image](https://user-images.githubusercontent.com/6019664/96720016-20bfc300-13a2-11eb-878f-db9326ae468b.png)

The blue outline shows the system recognizes it as a saved answer, and in the LTI tool the instructor can review and see the entered answers without any issues:

![image](https://user-images.githubusercontent.com/6019664/96720120-4b118080-13a2-11eb-9502-b8d230e28489.png)

After submitting the exam, the student can see their answers that were submitted again, with the appropriate formatting (same view as instructor mid-exam).

I have tested this with an older download of the exam (saved several months ago) and this displays answers just fine (even when using as a "safe replacement"), so I believe a recent update to the Numbas theme might have caused this to start happening.

**Comment by christianp** [comment]
@rogueosb thanks for reporting this. I'd had some vague reports of answers disappearing, but your report helped me work out it was to do with resuming attempts in progress.

I've fixed the problem - you'll need to update any packages downloaded since October 5th, sorry.
