### ISSUE TITLE
Penalty for showing steps

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#751]
I am confused about the current working of the penalty for showing steps. In [this question](https://numbas.mathcentre.ac.uk/question/76262/step-penalty/), if I enter the correct answer in the first, and an incorrect answer in the second gap, I get 1/2 points, as expected. See first screenshot. If I first show the hints and then enter the same anwers, I still get 1/2 points, even though the feedback says that points will be scaled down (second screenshot). Also, it says that the correct answer gets 2 marks instead of one.

![Screenshot from 2020-10-21 15-20-37](https://user-images.githubusercontent.com/668977/96727279-2c67b580-13b3-11eb-906c-f6ad5ba42282.png)
![Screenshot from 2020-10-21 15-20-54](https://user-images.githubusercontent.com/668977/96727600-85374e00-13b3-11eb-8c0b-de0ec5641762.png)

Something similar happens with [this other question](https://numbas.mathcentre.ac.uk/question/11698/equation-of-a-straight-line/) where after showing hints and then answering correctly the total is right, but it says that 4 marks were awarded for the submitted answer (third screenshot).
![Screenshot from 2020-10-21 15-30-22](https://user-images.githubusercontent.com/668977/96727302-312c6980-13b3-11eb-965b-9c64f639ba3e.png)

Thanks for looking into this (or pointing out that I am misunderstanding something...).

**Comment by christianp** [comment]
Thanks for reporting this. Again, it's something I inadvertently broke while adding in a new feature. Sorry you keep bumping into these things!
I've fixed the steps logic so it works as described (you'd get 0.5 marks in the second situation you posted), and I've added some unit tests so I don't break it again.
