### ISSUE TITLE
Should x_0 and x0 be considered identical?

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#753]
They're rendered exactly the same, so should they be considered identical? Maybe the version without an underscore should be normalised to the version with.

**Comment by sangwinc** [comment]
I had exactly the same quandary with STACK.  Currently they are different, but as you can see from the LaTeX generated from students' input the subtle difference between \[ x_1 \], and \[ {\it x_1} \] might be lost on some students...

**Comment by christianp** [comment]
Students regularly fail to notice (or don't know how to interpret) a string of letters in monospace font instead of italics, so I wouldn't want to rely on them noticing the difference between upright and italics!

**Comment by christianp** [comment]
This was resolved in 4839de7a11860e51fdf8d0c34cba65e787b16751 - `expand_juxtapositions` now rewrites `x1` to `x_1`, and this happens automatically in the mathematical expression part types' built-in marking algorithm.
