### ISSUE TITLE
Remark on "Sort student's answers before marking"

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#754]
The option works as documented, so this is not a bug but a feature suggestion/remark.

In a question like [this one](https://numbas.mathcentre.ac.uk/question/23076/complete-the-square-and-find-solutions/), which in Part b) asks for the two solution of a quadratic equation, the option works well if both submitted answers are correct.

But if one is correct, and the other one is not, it still depends on the "situation" whether 0 or 1 points are awarded (e.g. if 1 and 2 are the correct answers, then the submitted answer 1 and 3 in either order gives one point, but the answer -3 and 1 gives no point (again in either order, because it's sorted anyway). This behavior is hard to sell to the student, I think.

So I think what would be better suited to this and similar situations is an option implying that all the gaps are treated as a "multiset" rather than a tuple, i.e., the order is ignored, and the marking is determined by checking the size of the intersection of the collection of expected answers and the collection of submitted answers.

Thanks for all the great work. It's really fun to work with Numbas!

**Comment by christianp** [comment]
Yes, thanks for recording this. I implemented the feature, then realised that it was no good for the use case I had in mind!

**Comment by christianp** [comment]
The "set entry" answer type is asked for in #391. I'll close this issue now.
