### ISSUE TITLE
Explore Mode: "When correct" not working if a part has no marks

### ISSUE THREAD

**Issue by avohns** [numbas/Numbas#755]
Suppose you pose an explore mode question and you want the students to enter three numbers between 1 and 999, then let them proceed to the next part of an "explore mode" question if they entered three such numbers.
This should be possible using the "Availabilty"-option "When correct" for the second part, but this only works, if the first part assigns marks > 0 to the answers, which in some cases might not be desired.
If yo assign a mark of 0 to the questions in the first part, then the "correct"-trigger does not seem to become switch, leaving the second part unavailable.

**Comment by christianp** [comment]
I think I got the opposite behaviour to this: I created a part with two gaps, each with zero marks available. Answering one correctly but the other incorrectly produced full credit, which I think is wrong. I've just committed a change to the gap-fill marking algorithm to fix this.

Can you give me a link to a question that demonstrates the behaviour you described?

**Comment by avohns** [comment]
Here is a question that uses this (I went with 1 mark per gap as a workaround): https://numbas.mathcentre.ac.uk/question/77207/zahlendarstellung-am-quipu/preview/

**Comment by avohns** [comment]
Strange, I can't seem to reproduce it, I changed the values back to 0 for each mark an now it works... i could swear it did not work the first time.

**Comment by christianp** [comment]
OK, I'll close this then. Reopen it if you see the problem again.
