### ISSUE TITLE
Problem resuming a SCORM packaged exam

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#756]
When resuming [this exam](https://numbas.mathcentre.ac.uk/exam/17488/quadratische-gleichungen/) uploaded to a Moodle page as a SCORM package, I (also reproduced by other users) get the error 

Numbas has failed

Sorry, Numbas has encountered an error which means it can't continue. Below is a description of the error.
Numbas Error: Error loading question 7: Not a polynomial

The error message is always the same and always refers to question 7 of that exam. However, putting just that question and a second dummy question into an exam did not reproduce the problem, so there seems to be some interaction with one of the other questions(?)

Unfortunately, I do not currently have a setup where I could easily debug this further (and also, I am not sure how to go about that). Do you have an idea what could cause this? I could probably dig deeper and/or try to actually produce a smaller example with this behavior; any pointers would be helpful, though. Thanks!

Another (very small) thing I noticed when trying to put together a "minimal non-working example": For exams with only one question no Pause button is shown. It's probably not worth changing, but it might make sense to mention that in the documentation.

**Comment by christianp** [comment]
Thanks for reporting this. It turned out the polynomials extension on the mathcentre editor was out of date. I've updated it to the latest version, and that question now works.

I'll open a new issue about the pause button.
