### ISSUE TITLE
Does -((a+bi)/c) need brackets around the whole fraction when displayed in TeX?

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#757]
We had an expression `-(125+i)/3`, which was rendered in TeX as `-\frac{ 125 + i }{ 3 }`. I think that brackets around the fraction would make it clearer that the negation applies to the whole thing.
I'm not sure whether `- a/b` should always have brackets around the fraction, or just when there's an addition or subtraction on the top, or what.

**Comment by ugoertz** [comment]
As far as I can tell, $-\frac{ 125 + i }{ 3 }$ is fine and is the usual thing to write. I would definitively prefer not to have parentheses in this case.
First example in a printed text I found (from the Princeton Companion to Mathematics):
![IMG_20201102_125751](https://user-images.githubusercontent.com/668977/97866083-851c4400-1d0b-11eb-9254-a6ab628dae07.jpg)

**Comment by christianp** [comment]
Thanks, @ugoertz

**Comment by christianp** [comment]
OK, no extra parentheses.
