### ISSUE TITLE
An `iterations` JME function

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#759]
This might be a good generic function: `iterations(expression, variable_name, initial, times)`. It would repeatedly evaluate `expression`, replacing `variable_name` with the last value, and return a list of all the produced values.

Examples:

* `iterate(x+1, x, 0, 3) = [0,1,2,3]`
* `iterate(2x, x, 1, 3) = [1,2,4,8]`

**Comment by lorcanj** [comment]
Hi Christian, I was wondering if I could have a go at this? I'm completely new to open source contributions and pretty new to JS too but have been reading through the code base.

Could you advise what file this function should be kept and any other information you feel would be useful to know. Thanks

**Comment by christianp** [comment]
@lorcanj thank you very much offering to help. This isn't quite as easy to implement as I thought when I filed the issue, so I suggest you try something else before this one. Issue #770 is fairly straightforward to do - could you try that?

**Comment by lorcanj** [comment]
No problem, I'll try #770. Thanks.
