### ISSUE TITLE
Translate "Rows" and "Columns" in matrix resizing widget

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#767]
It would be nice if the words "Rows" and "Columns" in the widget for resizing the matrix in a "matrix entry" gap would be translated for non-English questions. I think it's here in the code (and the line after that for "Columns"):

https://github.com/numbas/Numbas/blob/b2443748e6c7a893f024a00de0207a0016495c2a/themes/default/files/scripts/answer-widgets.js#L545

Thanks! Best regards, Ulrich

**Comment by christianp** [comment]
Thanks for spotting this.

**Comment by christianp** [comment]
I've updated the list of terms on poeditor, so you can now enter translations for "Rows" and "Columns"
