### ISSUE TITLE
Problems with pausing a SCORM exam (in Moodle)

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#774]
I see the following unexpected (for me, that is) behavior when pausing and resuming an exam that is included as a SCORM package in a Moodle page. [Example exam showing this behavior](https://numbas.mathcentre.ac.uk/exam/18365/test-pause/).

There are two problems with this exam (and one minor point I will also mention):

(1) If I start the exam, enter the correct answer (so I get positive feedback), then pause and resume the exam, the entries have vanished and I get the message that the answer was not understood. This message is sent by the custom "Mark student's answer" script in the part's "Scripts" tab. The problem is that on resuming the exam, this script is run again, but the entries of this.studentAnswer are empty strings.

(2) With certain values, after pausing and resuming, correct answers are not accepted anymore. The reason is that the relevant question variables (complex numbers with fractional real and imaginary part) are not the same after resuming, but are truncated (e.g., 0.3333333333 instead of 0.3333333333333333). Since the student enters a fraction, the comparison (which uses Numbas.math.eq for these complex numbers) now fails (and of course, upon revealing the correct answer, displayed with fractions, the student is presented the weird outcome that she did enter the correct solution, but was not awarded points).

(3) The minor point: If I start the exam, and use "Try another question like this one", then pause and resume, I do not get back to the "new" question  from where I paused, but to the "old" one.

Some of this may be caused by the design of the SCORM protocol (about which I know basically nothing ...), so I am not sure whether this is really a Numbas issue. (Also, I suppose it would have been better to use a custom marking algorithm instead of this script anyway ... I hadn't really understood that yet when I wrote that question.)

Thank you for looking into this!

**Comment by christianp** [comment]
That exam doesn't exist any more.

I think that points 1 and 3 might be due to Moodle not having saved the data yet at the time you closed the page. If that's not the case, I'd like to see an example to reproduce the behaviour.

I think that point 2 has been dealt with recently.
