### ISSUE TITLE
Visual problem with matrix brackets on Safari 14

### ISSUE THREAD

**Issue by georgestagg** [numbas/Numbas#780]
The matrix part type has strange looking brackets on Safari 14. In Chrome it looks fine.
![Screenshot 2020-11-30 at 15 50 24](https://user-images.githubusercontent.com/982548/100631680-e42da280-3323-11eb-9ff6-9cc176c685ff.png)

**Comment by christianp** [comment]
This is definitely a safari rendering bug. I've added a clip-path to the brackets, which hides the incorrectly rendered opposite-side border at certain zoom levels.

I've been meaning to investigate whether it's possible to draw the brackets with an SVG instead. I'm not sure how stretching works.
