### ISSUE TITLE
Students aren't pressing "Submit" for a variety of reasons

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#783]
* "Submit" feels final, so students don't press it until they're sure. Would "Save" or "Check" look more like they can be redone?
* Students forget to press submit!
* The exam might run out of time before the student can submit their answer.
* Or their PC might crash and they don't get back in.

I think this is a user interface problem.

I think automatically submitting answers would be good: it's a principle in Numbas that you can submit as many times as you like, so just do that whenever the answer changes. It's not a good idea to show the feedback immediately, though - it would be distracting, and students might want to _ask_ for feedback rather than be automatically given it.

Parts where marking takes a long time or consumes lots of resources, such as the code marking extension, might not want to do this. Maybe the maximum frequency should be an attribute of the part that extensions can change?

Adaptive marking and explore mode also present problems: submitting one part can invalidate another.

Options:

* Show some help text like "You can submit your answer as many times as you like" under the submit part button when the answer has changed but not been submitted. This doesn't deal with the cases where students wanted to submit but the timer or a crash meant they couldn't.
* When the exam ends, try marking every part, and keep the feedback if that gives more credit than the part already has. This doesn't deal with cases where the exam doesn't end.
* Change "Submit" to "Save" or "Check". The exact text might depend on whether the student gets immediate feedback or not.
* Remove the submit button, and automatically submit when the answer changes (up to a max frequency). Where the submit button was, there will be some text like "Saved", to show that the answer is saved. When immediate feedback is available, there could be a "Show feedback" button.

**Comment by dshearman** [comment]
Would like to see some kind of auto submit if a timed test runs out of time. We've had a couple of instances of students forgetting to submit questions while doing a test then getting 0 for it because the timer ran out and nothing had been submitted.
Don Shearman
Western Sydney University

**Comment by christianp** [comment]
@dshearman are you using the LTI tool? If so, it can mark unsubmitted answers for all attempts - see https://numbas-lti-provider.readthedocs.io/en/latest/instructor/resources.html#remark.

**Comment by christianp** [comment]
I found out one reason why our students might be reluctant to press "Submit": in Canvas Quiz, the "Submit" button ends the quiz.

**Comment by christianp** [comment]
Can anyone think of a reason not to use "Save this answer" for the button label?

**Comment by dshearman** [comment]
Could this lead to confusion if a student changes an answer and then doesn't know which value is being taken for marking? I think my preferred option is the last one in the original post - automatically save answers with a "show feedback" button when appropriate.

Regards

Don Shearman | Mathematics Learning Advisor
Mathematics Education Support Hub (MESH)
Office of the Pro Vice-Chancellor (Learning Transformations)
P: +61 2 9685 9848 |E: ***@***.******@***.***>

Western Sydney University
Locked Bag 1797 Penrith NSW 2751 Australia
westernsydney.edu.au

[WSU_Logo_CMYK_45]

**Comment by zaript** [comment]
I would prefer the last option: whatever typed into the answer field last is an answer. Submitting the answer feels like a non-decision.

**Comment by christianp** [comment]
We still need to decide what to do with the feedback messages area: if parts are submitted automatically, then it needs to be a consistent size so that things in the page don't move after auto-submission.

**Comment by christianp** [comment]
Here's the current state of affairs, with a diagram linked to a multiple choice input:

https://github.com/numbas/Numbas/assets/19513/854ee41b-09de-4cb6-a759-a3c34ccc0772

I use the mouse to drag a point around. Immediately as I move it and the multiple choice input changes, the part is marked as dirty. 1 second after the input changes, the part is automatically submitted. 
If I interact with the checkboxes, the part is only automatically submitted once focus moves away from them.

**Comment by christianp** [comment]
It turns out that adding a `jxg_output: interpreted_answer` note to an extension part which refers to a diagram is sufficient to get it to auto-submit.

**Comment by christianp** [comment]
I've compiled the demo exam with this feature and put it online at https://www.staff.ncl.ac.uk/christian.perfect/numbas/automatic-submission-2024-05-29/.

Anybody who is interested, please give it a go and give us your feedback!

**Comment by christianp** [comment]
Automatic submission is now in v8.0, so I'm closing this.
