### ISSUE TITLE
Permutations extension, creating permutation from list

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#793]
In the Permutations extension, one can create a permutation by giving a list of numbers, but this list must be "zero-based", i.e., to get the transposition (2,3), say, one has to use permutation([0, 2, 1]). I suggest that this is explained in the documentation. (It might in fact be worth changing this behaviour? But of course that could break existing questions.)

If one creates a variable where 0 (or any "intermediate" number) does not occur, say permutation([1,2,3]) or permutation([0,2,3]), there is an uncaught javascript error (visible in the web developer console) since converting the list into a cycle presentation does not work. This breaks the variable editor (for the new variable, type "permutation" but no value is shown, and creating other variables does not work correctly) without displaying an error message in the Numbas interface.

**Comment by christianp** [comment]
Thanks for reporting this. I've added a note to the documentation about zero-indexing, and added a few lines to catch errors with badly-defined permutations.
