### ISSUE TITLE
Simplify doesn't always convert +- to -

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#800]
The expression `\[ \simplify[zerofactor, zeroterm]{x + (-2)*y + z + 0*u } \]` gives `x+-2y+z` (instead of `x-2y+z`). Similarly when the coefficients are replaced by variables. See [this question](https://numbas.mathcentre.ac.uk/question/87456/simplify-test/) for an example.

**Comment by christianp** [comment]
You need to include `basic` to rewrite `+-` to `-`.

**Comment by christianp** [comment]
Actually, I just did that and it didn't fix it. I'll investigate, thanks for reporting.

**Comment by christianp** [comment]
I think I've fixed it now. The rule didn't have "apply associativity" turned on, which meant it didn't separate out the other terms properly.
