### ISSUE TITLE
Capitalised functions marked as incorrect when "allow unknown function names" is off

### ISSUE THREAD

**Issue by georgestagg** [numbas/Numbas#808]
Create a mathematical expression part where the answer is something like `e^(-x)`.
When "Allow unknown function names" is on:
 * `exp(-x)` is marked as correct
 * `Exp(-x)` is marked as correct

But, when "Allow unknown function names" is off:
 * `exp(-x)` is marked as correct
 * `Exp(-x)` is marked as incorrect

I would expect "Exp" to be correct either way.

**Comment by christianp** [comment]
Thanks for spotting this. The `expand_juxtapositions` routine was case-sensitive, which it shouldn't be.
