### ISSUE TITLE
Gap Fills Not Being Added or Displayed Correctly

### ISSUE THREAD

**Issue by java12man** [numbas/Numbas#813]
When attempting to add a gap to a gap fill question the button is unresponsive.  Using direct source code does not show in the test run of the problem.

Even with gaps added to the part it is impossible to add the gap to the prompt for the student to enter a response.  The gap seems to be working as intended and it is simply a bug with the prompt.

**Comment by christianp** [comment]
Thanks for reporting this, and sorry I let this slip in: I updated the TinyMCE editor, but forgot to check the various bits I'd customised still worked. It should be working now.

**Comment by java12man** [comment]
Gap fills still have bugs, but only in the editor interface and using source code allows them to be used with full functionality.  Not a huge issue but it should be known.

Specifics:
Clicking gap fill button useless.  Clicking it does nothing.
Gap fills "sometimes" preview but other times just show as [[index]]. IE: "[[1]]"

**Comment by christianp** [comment]
Have you tried clearing your browser's cache?

**Comment by java12man** [comment]
Im so sorry for bothering you, that was it.  Thanks for the help.
