### ISSUE TITLE
Polynomials extension, display polynomial

### ISSUE THREAD

**Issue by ugoertz** [numbas/Numbas#841]
Displaying a polynomial `p` (defined using the `polynomials` extension) by `\var{p}` is currently broken, and in fact `latex(p)` generates an error (jme.display.texName is not a function). [Example question](https://numbas.mathcentre.ac.uk/question/99384/display-polynomial/)
One can work around it using `\var{latex(string(p))}` but that's a bit ugly (and removing the multiplication asterisks from `string(p)` makes it even more cumbersome).

**Comment by RocketingRacer** [comment]
A work around for this is to use `\var{expr(p)}` instead of `\var{string(p)}`.  Deals with the asterisks problem and can easily be done inline.
Best of luck

**Comment by christianp** [comment]
Thanks for reporting this. It broke with v6's new texifying code. I've fixed it now.
