### ISSUE TITLE
Numbas version in bin/numbas.py

### ISSUE THREAD

**Issue by jhoobergs** [numbas/Numbas#842]
The `NUMBAS_VERSION` is set to '5.2' in https://github.com/numbas/Numbas/blob/master/bin/numbas.py#L36
Shouldn't this be 6.0? 

I don't think that this really makes a huge difference?

**Comment by christianp** [comment]
Ah! Well spotted. I should have increased that when I tagged v6.0. Thanks for pointing it out.
