### ISSUE TITLE
Results page shifted to the left when ending an exam on Safari

### ISSUE THREAD

**Issue by georgestagg** [numbas/Numbas#854]
<img width="1082" alt="Screenshot 2021-09-27 at 13 23 45" src="https://user-images.githubusercontent.com/982548/134907297-55540bda-3fd5-4c01-a5cd-bcafb630a266.png">

**Comment by christianp** [comment]
I think this is a Safari bug.

It only happened for me when the viewport is less than 992px wide. Toggling on and off the `margin-left` property on the `.row` element containing the table made it show up in the right place. It stayed in the right place when I resized the window, until it went over the 992px breakpoint. When I made it narrower than that again, the table was drawn in the wrong place again.
