### ISSUE TITLE
Marking: an add_credit_if function

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#859]
This is a common pattern: I have a list of independent criteria that a student's answer must fulfil. For each of them, I want to add a certain amount of credit if it's satisfied, and give some negative feedback otherwise.

At the moment, it's possible with this:

```
if(criterion_satisfied,
  add_credit(amount, "You did it!")
, negative_feedback("You didn't do it.")
)
```

It would be convenient to have a function `add_credit_if(condition, amount, positive_feedback, negative_feedback)` which is equivalent to the above code.

**Comment by hafhaf10** [comment]
Hi, I would like to try.

**Comment by christianp** [comment]
@hafhaf10 thanks for offering to help! Please look at our [guide on contributing code to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code). The marking functions are defined in [`runtime/scripts/marking.js`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/marking.js#L178) - you should add a new function `'add_credit_if'`.
