### ISSUE TITLE
Default theme: make sure the page looks sensible when the stylesheet fails to load

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#880]
When the stylesheet fails to load, maybe due to a bad internet connection, all sorts of stuff is visible that shouldn't be - modals, error messages, and so on. 

I think the `index.html` should set `display:none` on everything except for the loading message, which is then overridden by the stylesheet.

**Comment by Arti-0** [comment]
The `display:none` would be a good measure would certainly work fine but try to fix the issue to its core. When you load the page, the stylesheet should be applied anyway. I think a `z-index:_highvalue_` on the loading message with a `background:_anythingreally_` would probably be fine.

**Comment by christianp** [comment]
Fixed by 285f537e
