### ISSUE TITLE
Custom marking variable named "marks" breaks the marking algorithm for a "Choose one from a list" gapfill

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#890]
Example of the problem here: https://numbas.mathcentre.ac.uk/question/116540/choose-one-from-a-list-in-a-gap/

We had a question using the variable name `marks` in the custom marking matrix field for a _Choose one from a list_ question. This seems to break the marking algorithm (which also uses a variable `marks`), though only when presented as a gapfill, as illustrated in the above example.

**Comment by christianp** [comment]
I made issue #892 before seeing this! That issue has my recommended solution, so I'll close this one.
