### ISSUE TITLE
Throw an error if a marking parameter has the same name as a variable already defined in the scope

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#892]
We had a question with a variable called `marks`, holding the marking matrix for an MCQ part. The marking parameters for a part include a variable `marks`, holding the number of marks available for the part.

This should have thrown an error. I think catching this at the point that the marking parameters are added to the scope is the right thing to do.

**Comment by LexxLuey** [comment]
Good day. I am new to open source contribution. Can I work on this?

**Comment by christianp** [comment]
Hi @LexxLuey, thanks for offering to help. Yes, feel free to work on any open issue tagged "good first issue".

Please have a look at our [page on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/).

To implement this, I think that it would make sense to a check to the `mark_answers` function in [`runtime/scripts/part.js`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/part.js#L1772), comparing the variables defined in the scope with the entries in the marking parameters object.
