### ISSUE TITLE
Printable worksheet theme is broken

### ISSUE THREAD

**Issue by ccrua** [numbas/Numbas#897]
1. MathJax equations no longer display correctly with printable worksheet theme.

2. Unnecessary feedback text is displayed: "Your answer is being marked. Please wait." and "This feedback is based on your last submitted answer. Submit your changed answer to get updated feedback."

3. Sometimes throws TypeError: Unable to process binding "autosize: function(){return true }" Message: Numbas.display.measureText is not a function

**Comment by christianp** [comment]
Sorry about this. I didn't copy my fix for #896 into the printed worksheet theme. I've done that now, and checked that printed worksheets display properly.
