### ISSUE TITLE
Remove "Not marked" from printable worksheet format

### ISSUE THREAD

**Issue by prowlett** [numbas/Numbas#904]
I've been asked to talk about my [partially-automated assessment thing](https://doi.org/10.1080/0020739X.2020.1822554), which I've not thought about in ages. The talk is next week so I'm making slides and redoing my screenshots to be in the current interface. 

When I generate a printable worksheet, it has the words "Not marked" under each question. Can this be removed?

![Screenshot from 2022-04-21 07-03-17](https://user-images.githubusercontent.com/5698564/164385306-16d4691e-d767-423a-91f6-e4a934f80f10.png)

**Comment by msgj603** [comment]
I see the number of marks available in my printable worksheet. Please see example below:

![image](https://user-images.githubusercontent.com/5709336/164452821-15c8763f-e120-421e-8199-ed5ce176b739.png)

**Comment by prowlett** [comment]
Ah, interesting! I didn't set a number of marks, and I can think of use cases where I might want marks displayed or not. I think that this item should display if and only there is a number of marks set.

**Comment by christianp** [comment]
I've changed the printable worksheet theme so the "not marked" text is only shown if "show maximum marks" is turned on in the exam's feedback settings.
