### ISSUE TITLE
Increase the feedback message width or set figure size

### ISSUE THREAD

**Issue by chrismgraham** [numbas/Numbas#949]
At the moment, the default figure size from matplotlib gives rise to horizontal scrollbars in the feedback message. I guess we could set the figure size, but is it possible for the feedback message div be made wider (even if just for the programming extension and/or if there is an image in the output)?

Extending feedbackMessages to max-width: 60em and max-height: 40em is much more accommodating for figures.

**Comment by christianp** [comment]
I think the max-width was only to ensure that the feedback icons on the left line up. If we move them to the right, then that's not a problem.

I'm not sure how I feel about the max-height. My inclination is to get rid of it, but it must be there for a reason.

How do you feel about this?

![image](https://user-images.githubusercontent.com/19513/193562255-7fcac87f-605e-4712-9cba-694dc28b69c2.png)

**Comment by aarchiba** [comment]
This looks like an improvement, and would help with tracebacks as well, or print statement output where appropriate (although line breaks aren't respected there).

**Comment by christianp** [comment]
@aarchiba can you explain what you mean about line breaks not being respected?

**Comment by chrismgraham** [comment]
Looks good to me (and got to practice some German). With regards to the height, I do find that with output and multiple marking tests in the programming extension, it's often necessary to scroll. I can't think of a downside to removing it, though a max-height on stdout/err in case a student prints something inordinately large might be an idea

**Comment by christianp** [comment]
We definitely need to set some max dimensions. At the moment I think it should apply to individual feedback items, rather than the whole feedback area.

**Comment by aarchiba** [comment]
> @aarchiba can you explain what you mean about line breaks not being respected?

```python
print("message 1")
print("message 2")
```
results in the output area containing "message 1 message 2"; presumably this has to do with stdout being interpreted as HTML. (I haven't tried sending any really interesting HTML yet.)

**Comment by christianp** [comment]
When I enter that code, it puts the messages on separate lines, as I expected:
![image](https://user-images.githubusercontent.com/19513/193758208-99288e99-9e97-404d-91cd-03604b7af8b4.png)

The stdout isn't interpreted as HTML. Could this be a browser bug? Which browser are you using? I used Firefox.

**Comment by aarchiba** [comment]
Aha, I was including print statements in the postamble to help troubleshooting, and they don't get formatted that way.

This is clearly a separate issue, though.

**Comment by aarchiba** [comment]
As far as the original issue goes, we did indeed have a class full of students who either squinted and scrolled to figure out what their plots looked like, or didn't even realize we were showing their output plot.

**Comment by aarchiba** [comment]
Is there any chance of this fix making it in to the code base before I finish teaching?

**Comment by christianp** [comment]
Probably not, sorry - I've got a million things on at the moment and the change to the layout is in the development branch, which needs a lot of testing before we merge it in and start using it with students.
