### ISSUE TITLE
A box for adding direct colour code

### ISSUE THREAD

**Issue by Asharma538** [numbas/Numbas#951]
![image](https://user-images.githubusercontent.com/102324067/194154770-aac63060-e588-406b-b053-bcdf60dfd727.png)
An input box can be added here with the background colour option so that if the user wants to add a colour code directly like #e1e2e1
he/she can do so.

**Comment by christianp** [comment]
I don't think this is necessary: in Firefox, at least, when I open the colour picker, there's a "Custom" button that lets you type in a hex code:

![image](https://user-images.githubusercontent.com/19513/194235140-7c20b766-d21a-4d9b-b00b-c309116c836d.png)

This is really something that we can rely on the browser-provided colour picker to enable.
