### ISSUE TITLE
Submit all parts on "choose one from a list" can produce "answered" status on unanswered parts

### ISSUE THREAD

**Issue by aarchiba** [numbas/Numbas#953]
I have a question with many "choose one from a list" parts. I answered some but not others and hit "submit all". No message was emitted, and now NUMBAS claims all parts have been "answered", even the ones where I never selected an option. The ones that were actually answered can be distinguished because the selected option is highlighted, but the fact that it claims all were answered is confusing.

**Comment by aarchiba** [comment]
This is in contrast to the "code" part, where "submit all parts" leaves untouched parts "unanswered" and also leaves any that don't pass validation tests "unanswered".

**Comment by christianp** [comment]
Can you give me a link to a question where this happens?

**Comment by aarchiba** [comment]
https://numbas.mathcentre.ac.uk/question/share/view/21d0544a-be64-4b48-b999-b9f299366ffe - use "test run", answer one or two, hit "submit", and all the unanswered ones are marked as answered but wrong. In a summative setting, you don't even get the feedback that they're wrong.

**Comment by christianp** [comment]
Thanks, that helped me solve it.
