### ISSUE TITLE
The feedback/testimonial cards are of uneven height. 

### ISSUE THREAD

**Issue by zetabug** [numbas/Numbas#959]
Look at how one of the cards is smaller than others. 
![Screenshot (7)](https://user-images.githubusercontent.com/72355377/198278900-7ad1f327-95de-4442-9330-293062f57a52.png)

can be fixed in this manner.
![Screenshot (6)](https://user-images.githubusercontent.com/72355377/198279148-faea2bb0-a4ef-4ad3-b24d-092631ef468a.png)

**Comment by christianp** [comment]
Hi,
Thanks for offering to help, but the code for the Numbas website is not public. This repository contains the Numbas runtime.
