### ISSUE TITLE
An empty 'marks' field should default to 0

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#979]
At the moment, it seems that leaving the field completely empty leads to the part's `marks` attribute being the empty string, which then produces `NaN` credit when the part is submitted.

**Comment by likileads** [comment]
Hi @christianp I wish to work on this issue.
Can you please guide me where to get started with.

**Comment by christianp** [comment]
Hi @likileads, thanks for offering to help!
First you should set up a development environment. There are some instructions at https://docs.numbas.org.uk/en/latest/development/installation.html.

Once you've done that, I think that adding a line like `this.marks = this.marks || 0` to [`Numbas.Part.finaliseLoad`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/part.js#L350) would resolve this.

To test this, use the editor to create a question with a single part, and empty the "Marks" field. When you run the question, `Numbas.exam.currentQuestion.parts[0].marks` should evaluate to `0` instead of `''`.
