### ISSUE TITLE
In sequence mode, have an entry above question 1 in the nav to show the introduction again

### ISSUE THREAD

**Issue by christianp** [numbas/Numbas#990]
At the moment, there's no way of seeing the introduction text again after starting the exam.

**Comment by alt-shreya** [comment]
hey is this taken? I'd like to work on it

**Comment by christianp** [comment]
@alt-shreya thanks for offering to help! Please look at [our guide on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code).
